use serde::{Deserialize, Serialize};
use std::{collections::HashMap, error::Error, hash::Hash};

// declarations
// ======================

pub struct Foo {
    x: i32,
    y: i32,
}

// ======================

/// Token
/// must implement Clone and Token trait
/// Token trait is used to convert a token to a tree node
pub trait Token: Clone {
    fn to_tree_node(&self) -> ParsingTreeNode;
}

pub struct ParsingTreeNode {
    pub symbol_type: String,
    pub data: String,
    pub children: Vec<ParsingTreeNode>,
}

impl ParsingTreeNode {
    pub fn build(symbol_type: String, data: String, children: Vec<ParsingTreeNode>) -> Self {
        ParsingTreeNode {
            symbol_type,
            data,
            children,
        }
    }
}

/// NodePair
/// a pair of a node and a state.
/// (TreeNode, state)
pub struct NodePair(ParsingTreeNode, usize);
impl NodePair {
    pub fn new(node: ParsingTreeNode, state: usize) -> Self {
        NodePair(node, state)
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ReduceDerivation {
    pub left: String,
    pub right: Vec<String>,
}

impl PartialEq for ReduceDerivation {
    fn eq(&self, other: &Self) -> bool {
        self.left == other.left && self.right == other.right
    }
}

impl Eq for ReduceDerivation {}

impl Hash for ReduceDerivation {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.left.hash(state);
        self.right.hash(state);
    }
}

impl ReduceDerivation {
    pub fn build(left: String, right: Vec<String>) -> Self {
        ReduceDerivation { left, right }
    }
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Action {
    Shift(usize),
    Reduce(ReduceDerivation),
    Accept,
    Error,
}

#[derive(Serialize, Deserialize)]
pub struct State {
    pub actions: HashMap<String, Action>,
}

impl State {
    pub fn new() -> Self {
        State {
            actions: HashMap::new(),
        }
    }
}

#[derive(Serialize, Deserialize, Default)]
pub struct ActionTable {
    pub states: Vec<State>,
}

impl ActionTable {
    pub fn get_action(&self, state: usize, symbol: &str) -> Option<&Action> {
        self.states[state].actions.get(symbol)
    }
}

#[derive(Default)]
pub struct RParser {
    action_table: ActionTable,
    handlers: HashMap<ReduceDerivation, Box<dyn Fn(Vec<String>) -> String>>,
    // variables
    // ======================
    pub a: i32,
    pub b: i64,
    // ======================
}

impl RParser {
    pub const END_SYMBOL: &'static str = "__$__";
    pub const EPSILON_SYMBOL: &'static str = "__EPSILON__";
    pub const DUMMY_START_SYMBOL: &'static str = "__DUMMY_START__";

    pub fn new() -> Self {
        // action table generated by rparser
        // ======================
        let action_table: ActionTable =  serde_json::from_str(r#"{"states":[{"actions":{"__$__":"Accept","program":{"Shift":1},"block":{"Shift":2},"left_curly_brace":{"Shift":3},"S":{"Shift":89}}},{"actions":{"__$__":{"Reduce":{"left":"S","right":["program"]}}}},{"actions":{"__$__":{"Reduce":{"left":"program","right":["block"]}}}},{"actions":{"left_curly_brace":{"Reduce":{"left":"decls","right":[]}},"while":{"Reduce":{"left":"decls","right":[]}},"basic":{"Reduce":{"left":"decls","right":[]}},"do":{"Reduce":{"left":"decls","right":[]}},"id":{"Reduce":{"left":"decls","right":[]}},"if":{"Reduce":{"left":"decls","right":[]}},"break":{"Reduce":{"left":"decls","right":[]}},"decls":{"Shift":4}}},{"actions":{"right_curly_brace":{"Reduce":{"left":"stmts","right":[]}},"do":{"Reduce":{"left":"stmts","right":[]}},"basic":{"Shift":12},"left_curly_brace":{"Reduce":{"left":"stmts","right":[]}},"if":{"Reduce":{"left":"stmts","right":[]}},"type":{"Shift":5},"while":{"Reduce":{"left":"stmts","right":[]}},"decl":{"Shift":11},"break":{"Reduce":{"left":"stmts","right":[]}},"id":{"Reduce":{"left":"stmts","right":[]}},"stmts":{"Shift":13}}},{"actions":{"id":{"Shift":6},"[":{"Shift":8}}},{"actions":{";":{"Shift":7}}},{"actions":{"left_curly_brace":{"Reduce":{"left":"decl","right":["type","id",";"]}},"id":{"Reduce":{"left":"decl","right":["type","id",";"]}},"basic":{"Reduce":{"left":"decl","right":["type","id",";"]}},"while":{"Reduce":{"left":"decl","right":["type","id",";"]}},"do":{"Reduce":{"left":"decl","right":["type","id",";"]}},"if":{"Reduce":{"left":"decl","right":["type","id",";"]}},"break":{"Reduce":{"left":"decl","right":["type","id",";"]}}}},{"actions":{"num":{"Shift":9}}},{"actions":{"]":{"Shift":10}}},{"actions":{"[":{"Reduce":{"left":"type","right":["type","[","num","]"]}},"id":{"Reduce":{"left":"type","right":["type","[","num","]"]}}}},{"actions":{"do":{"Reduce":{"left":"decls","right":["decls","decl"]}},"left_curly_brace":{"Reduce":{"left":"decls","right":["decls","decl"]}},"break":{"Reduce":{"left":"decls","right":["decls","decl"]}},"if":{"Reduce":{"left":"decls","right":["decls","decl"]}},"basic":{"Reduce":{"left":"decls","right":["decls","decl"]}},"while":{"Reduce":{"left":"decls","right":["decls","decl"]}},"id":{"Reduce":{"left":"decls","right":["decls","decl"]}}}},{"actions":{"id":{"Reduce":{"left":"type","right":["basic"]}},"[":{"Reduce":{"left":"type","right":["basic"]}}}},{"actions":{"while":{"Shift":17},"right_curly_brace":{"Shift":15},"do":{"Shift":78},"id":{"Shift":16},"left_curly_brace":{"Shift":3},"block":{"Shift":71},"stmt":{"Shift":14},"loc":{"Shift":67},"break":{"Shift":76},"if":{"Shift":72}}},{"actions":{"do":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"break":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"while":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"right_curly_brace":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"id":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"if":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"left_curly_brace":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}}}},{"actions":{"right_curly_brace":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"while":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"else":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"do":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"__$__":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"id":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"break":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"if":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"left_curly_brace":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}}}},{"actions":{"-":{"Reduce":{"left":"loc","right":["id"]}},"/":{"Reduce":{"left":"loc","right":["id"]}},";":{"Reduce":{"left":"loc","right":["id"]}},"||":{"Reduce":{"left":"loc","right":["id"]}},"<=":{"Reduce":{"left":"loc","right":["id"]}},"=":{"Reduce":{"left":"loc","right":["id"]}},"&&":{"Reduce":{"left":"loc","right":["id"]}},"<":{"Reduce":{"left":"loc","right":["id"]}},">=":{"Reduce":{"left":"loc","right":["id"]}},">":{"Reduce":{"left":"loc","right":["id"]}},"!=":{"Reduce":{"left":"loc","right":["id"]}},"[":{"Reduce":{"left":"loc","right":["id"]}},"+":{"Reduce":{"left":"loc","right":["id"]}},"==":{"Reduce":{"left":"loc","right":["id"]}},")":{"Reduce":{"left":"loc","right":["id"]}},"*":{"Reduce":{"left":"loc","right":["id"]}}}},{"actions":{"(":{"Shift":18}}},{"actions":{"unary":{"Shift":33},"factor":{"Shift":37},"real":{"Shift":19},"bool":{"Shift":65},"join":{"Shift":62},"loc":{"Shift":23},"rel":{"Shift":30},"id":{"Shift":16},"true":{"Shift":36},"term":{"Shift":47},"(":{"Shift":29},"expr":{"Shift":31},"!":{"Shift":22},"equality":{"Shift":20},"-":{"Shift":34},"false":{"Shift":28},"num":{"Shift":27}}},{"actions":{"-":{"Reduce":{"left":"factor","right":["real"]}},"+":{"Reduce":{"left":"factor","right":["real"]}},"&&":{"Reduce":{"left":"factor","right":["real"]}},"*":{"Reduce":{"left":"factor","right":["real"]}},">":{"Reduce":{"left":"factor","right":["real"]}},")":{"Reduce":{"left":"factor","right":["real"]}},"<=":{"Reduce":{"left":"factor","right":["real"]}},">=":{"Reduce":{"left":"factor","right":["real"]}},"!=":{"Reduce":{"left":"factor","right":["real"]}},";":{"Reduce":{"left":"factor","right":["real"]}},"<":{"Reduce":{"left":"factor","right":["real"]}},"/":{"Reduce":{"left":"factor","right":["real"]}},"||":{"Reduce":{"left":"factor","right":["real"]}},"==":{"Reduce":{"left":"factor","right":["real"]}}}},{"actions":{"||":{"Reduce":{"left":"join","right":["equality"]}},"&&":{"Reduce":{"left":"join","right":["equality"]}},")":{"Reduce":{"left":"join","right":["equality"]}},"!=":{"Shift":21},"==":{"Shift":60},";":{"Reduce":{"left":"join","right":["equality"]}}}},{"actions":{"term":{"Shift":47},"num":{"Shift":27},"false":{"Shift":28},"real":{"Shift":19},"factor":{"Shift":37},"true":{"Shift":36},"rel":{"Shift":64},"expr":{"Shift":31},"loc":{"Shift":23},"id":{"Shift":16},"(":{"Shift":29},"unary":{"Shift":33},"!":{"Shift":22},"-":{"Shift":34}}},{"actions":{"unary":{"Shift":63},"!":{"Shift":22},"(":{"Shift":29},"num":{"Shift":27},"id":{"Shift":16},"real":{"Shift":19},"true":{"Shift":36},"factor":{"Shift":37},"-":{"Shift":34},"loc":{"Shift":23},"false":{"Shift":28}}},{"actions":{"!=":{"Reduce":{"left":"factor","right":["loc"]}},"==":{"Reduce":{"left":"factor","right":["loc"]}},"+":{"Reduce":{"left":"factor","right":["loc"]}},"<":{"Reduce":{"left":"factor","right":["loc"]}},"[":{"Shift":24},"*":{"Reduce":{"left":"factor","right":["loc"]}},"/":{"Reduce":{"left":"factor","right":["loc"]}},">=":{"Reduce":{"left":"factor","right":["loc"]}},";":{"Reduce":{"left":"factor","right":["loc"]}},")":{"Reduce":{"left":"factor","right":["loc"]}},"<=":{"Reduce":{"left":"factor","right":["loc"]}},">":{"Reduce":{"left":"factor","right":["loc"]}},"||":{"Reduce":{"left":"factor","right":["loc"]}},"-":{"Reduce":{"left":"factor","right":["loc"]}},"&&":{"Reduce":{"left":"factor","right":["loc"]}}}},{"actions":{"num":{"Shift":25}}},{"actions":{"]":{"Shift":26}}},{"actions":{"/":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"*":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"[":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},";":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"&&":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"<=":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"=":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"!=":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},">=":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},")":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"==":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"+":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"||":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},">":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"-":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"<":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}}}},{"actions":{"+":{"Reduce":{"left":"factor","right":["num"]}},"<":{"Reduce":{"left":"factor","right":["num"]}},"-":{"Reduce":{"left":"factor","right":["num"]}},"<=":{"Reduce":{"left":"factor","right":["num"]}},">=":{"Reduce":{"left":"factor","right":["num"]}},"!=":{"Reduce":{"left":"factor","right":["num"]}},"*":{"Reduce":{"left":"factor","right":["num"]}},";":{"Reduce":{"left":"factor","right":["num"]}},"&&":{"Reduce":{"left":"factor","right":["num"]}},"==":{"Reduce":{"left":"factor","right":["num"]}},"||":{"Reduce":{"left":"factor","right":["num"]}},")":{"Reduce":{"left":"factor","right":["num"]}},"/":{"Reduce":{"left":"factor","right":["num"]}},">":{"Reduce":{"left":"factor","right":["num"]}}}},{"actions":{"-":{"Reduce":{"left":"factor","right":["false"]}},"/":{"Reduce":{"left":"factor","right":["false"]}},"*":{"Reduce":{"left":"factor","right":["false"]}},"!=":{"Reduce":{"left":"factor","right":["false"]}},"<":{"Reduce":{"left":"factor","right":["false"]}},">":{"Reduce":{"left":"factor","right":["false"]}},"&&":{"Reduce":{"left":"factor","right":["false"]}},")":{"Reduce":{"left":"factor","right":["false"]}},">=":{"Reduce":{"left":"factor","right":["false"]}},"||":{"Reduce":{"left":"factor","right":["false"]}},"+":{"Reduce":{"left":"factor","right":["false"]}},"==":{"Reduce":{"left":"factor","right":["false"]}},"<=":{"Reduce":{"left":"factor","right":["false"]}},";":{"Reduce":{"left":"factor","right":["false"]}}}},{"actions":{"bool":{"Shift":54},"term":{"Shift":47},"real":{"Shift":19},"unary":{"Shift":33},"-":{"Shift":34},"equality":{"Shift":20},"factor":{"Shift":37},"expr":{"Shift":31},"true":{"Shift":36},"false":{"Shift":28},"rel":{"Shift":30},"id":{"Shift":16},"(":{"Shift":29},"join":{"Shift":62},"loc":{"Shift":23},"num":{"Shift":27},"!":{"Shift":22}}},{"actions":{"==":{"Reduce":{"left":"equality","right":["rel"]}},"&&":{"Reduce":{"left":"equality","right":["rel"]}},";":{"Reduce":{"left":"equality","right":["rel"]}},"||":{"Reduce":{"left":"equality","right":["rel"]}},"!=":{"Reduce":{"left":"equality","right":["rel"]}},")":{"Reduce":{"left":"equality","right":["rel"]}}}},{"actions":{"!=":{"Reduce":{"left":"rel","right":["expr"]}},"-":{"Shift":32},">=":{"Shift":43},"+":{"Shift":45},"&&":{"Reduce":{"left":"rel","right":["expr"]}},"==":{"Reduce":{"left":"rel","right":["expr"]}},"<":{"Shift":50},"<=":{"Shift":52},";":{"Reduce":{"left":"rel","right":["expr"]}},")":{"Reduce":{"left":"rel","right":["expr"]}},">":{"Shift":48},"||":{"Reduce":{"left":"rel","right":["expr"]}}}},{"actions":{"(":{"Shift":29},"-":{"Shift":34},"true":{"Shift":36},"real":{"Shift":19},"num":{"Shift":27},"term":{"Shift":38},"id":{"Shift":16},"false":{"Shift":28},"factor":{"Shift":37},"loc":{"Shift":23},"unary":{"Shift":33},"!":{"Shift":22}}},{"actions":{"!=":{"Reduce":{"left":"term","right":["unary"]}},"*":{"Reduce":{"left":"term","right":["unary"]}},"&&":{"Reduce":{"left":"term","right":["unary"]}},">":{"Reduce":{"left":"term","right":["unary"]}},">=":{"Reduce":{"left":"term","right":["unary"]}},"-":{"Reduce":{"left":"term","right":["unary"]}},")":{"Reduce":{"left":"term","right":["unary"]}},"/":{"Reduce":{"left":"term","right":["unary"]}},"<":{"Reduce":{"left":"term","right":["unary"]}},"<=":{"Reduce":{"left":"term","right":["unary"]}},"+":{"Reduce":{"left":"term","right":["unary"]}},";":{"Reduce":{"left":"term","right":["unary"]}},"||":{"Reduce":{"left":"term","right":["unary"]}},"==":{"Reduce":{"left":"term","right":["unary"]}}}},{"actions":{"id":{"Shift":16},"real":{"Shift":19},"num":{"Shift":27},"false":{"Shift":28},"unary":{"Shift":35},"loc":{"Shift":23},"(":{"Shift":29},"!":{"Shift":22},"factor":{"Shift":37},"true":{"Shift":36},"-":{"Shift":34}}},{"actions":{")":{"Reduce":{"left":"unary","right":["-","unary"]}},"!=":{"Reduce":{"left":"unary","right":["-","unary"]}},"*":{"Reduce":{"left":"unary","right":["-","unary"]}},"/":{"Reduce":{"left":"unary","right":["-","unary"]}},"&&":{"Reduce":{"left":"unary","right":["-","unary"]}},"<=":{"Reduce":{"left":"unary","right":["-","unary"]}},">=":{"Reduce":{"left":"unary","right":["-","unary"]}},";":{"Reduce":{"left":"unary","right":["-","unary"]}},"<":{"Reduce":{"left":"unary","right":["-","unary"]}},"||":{"Reduce":{"left":"unary","right":["-","unary"]}},"+":{"Reduce":{"left":"unary","right":["-","unary"]}},">":{"Reduce":{"left":"unary","right":["-","unary"]}},"==":{"Reduce":{"left":"unary","right":["-","unary"]}},"-":{"Reduce":{"left":"unary","right":["-","unary"]}}}},{"actions":{"&&":{"Reduce":{"left":"factor","right":["true"]}},";":{"Reduce":{"left":"factor","right":["true"]}},")":{"Reduce":{"left":"factor","right":["true"]}},"||":{"Reduce":{"left":"factor","right":["true"]}},"-":{"Reduce":{"left":"factor","right":["true"]}},"<=":{"Reduce":{"left":"factor","right":["true"]}},"*":{"Reduce":{"left":"factor","right":["true"]}},">":{"Reduce":{"left":"factor","right":["true"]}},"+":{"Reduce":{"left":"factor","right":["true"]}},"==":{"Reduce":{"left":"factor","right":["true"]}},"<":{"Reduce":{"left":"factor","right":["true"]}},"/":{"Reduce":{"left":"factor","right":["true"]}},"!=":{"Reduce":{"left":"factor","right":["true"]}},">=":{"Reduce":{"left":"factor","right":["true"]}}}},{"actions":{"*":{"Reduce":{"left":"unary","right":["factor"]}},"<":{"Reduce":{"left":"unary","right":["factor"]}},")":{"Reduce":{"left":"unary","right":["factor"]}},"<=":{"Reduce":{"left":"unary","right":["factor"]}},"+":{"Reduce":{"left":"unary","right":["factor"]}},"==":{"Reduce":{"left":"unary","right":["factor"]}},"&&":{"Reduce":{"left":"unary","right":["factor"]}},">":{"Reduce":{"left":"unary","right":["factor"]}},">=":{"Reduce":{"left":"unary","right":["factor"]}},"/":{"Reduce":{"left":"unary","right":["factor"]}},"!=":{"Reduce":{"left":"unary","right":["factor"]}},";":{"Reduce":{"left":"unary","right":["factor"]}},"||":{"Reduce":{"left":"unary","right":["factor"]}},"-":{"Reduce":{"left":"unary","right":["factor"]}}}},{"actions":{"*":{"Shift":39},"-":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"!=":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"/":{"Shift":41},")":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"+":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"<":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"==":{"Reduce":{"left":"expr","right":["expr","-","term"]}},">":{"Reduce":{"left":"expr","right":["expr","-","term"]}},">=":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"<=":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"&&":{"Reduce":{"left":"expr","right":["expr","-","term"]}},";":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"||":{"Reduce":{"left":"expr","right":["expr","-","term"]}}}},{"actions":{"-":{"Shift":34},"unary":{"Shift":40},"real":{"Shift":19},"loc":{"Shift":23},"factor":{"Shift":37},"true":{"Shift":36},"id":{"Shift":16},"(":{"Shift":29},"!":{"Shift":22},"num":{"Shift":27},"false":{"Shift":28}}},{"actions":{"||":{"Reduce":{"left":"term","right":["term","*","unary"]}},">":{"Reduce":{"left":"term","right":["term","*","unary"]}},"+":{"Reduce":{"left":"term","right":["term","*","unary"]}},")":{"Reduce":{"left":"term","right":["term","*","unary"]}},"*":{"Reduce":{"left":"term","right":["term","*","unary"]}},"&&":{"Reduce":{"left":"term","right":["term","*","unary"]}},"!=":{"Reduce":{"left":"term","right":["term","*","unary"]}},"==":{"Reduce":{"left":"term","right":["term","*","unary"]}},">=":{"Reduce":{"left":"term","right":["term","*","unary"]}},"/":{"Reduce":{"left":"term","right":["term","*","unary"]}},";":{"Reduce":{"left":"term","right":["term","*","unary"]}},"<":{"Reduce":{"left":"term","right":["term","*","unary"]}},"-":{"Reduce":{"left":"term","right":["term","*","unary"]}},"<=":{"Reduce":{"left":"term","right":["term","*","unary"]}}}},{"actions":{"!":{"Shift":22},"id":{"Shift":16},"factor":{"Shift":37},"loc":{"Shift":23},"num":{"Shift":27},"real":{"Shift":19},"(":{"Shift":29},"unary":{"Shift":42},"true":{"Shift":36},"-":{"Shift":34},"false":{"Shift":28}}},{"actions":{"||":{"Reduce":{"left":"term","right":["term","/","unary"]}},"!=":{"Reduce":{"left":"term","right":["term","/","unary"]}},"&&":{"Reduce":{"left":"term","right":["term","/","unary"]}},">=":{"Reduce":{"left":"term","right":["term","/","unary"]}},"/":{"Reduce":{"left":"term","right":["term","/","unary"]}},">":{"Reduce":{"left":"term","right":["term","/","unary"]}},"<=":{"Reduce":{"left":"term","right":["term","/","unary"]}},";":{"Reduce":{"left":"term","right":["term","/","unary"]}},"*":{"Reduce":{"left":"term","right":["term","/","unary"]}},"+":{"Reduce":{"left":"term","right":["term","/","unary"]}},"-":{"Reduce":{"left":"term","right":["term","/","unary"]}},")":{"Reduce":{"left":"term","right":["term","/","unary"]}},"<":{"Reduce":{"left":"term","right":["term","/","unary"]}},"==":{"Reduce":{"left":"term","right":["term","/","unary"]}}}},{"actions":{"id":{"Shift":16},"term":{"Shift":47},"num":{"Shift":27},"expr":{"Shift":44},"true":{"Shift":36},"false":{"Shift":28},"!":{"Shift":22},"(":{"Shift":29},"loc":{"Shift":23},"unary":{"Shift":33},"real":{"Shift":19},"-":{"Shift":34},"factor":{"Shift":37}}},{"actions":{";":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},")":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},"&&":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},"||":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},"+":{"Shift":45},"==":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},"!=":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},"-":{"Shift":32}}},{"actions":{"true":{"Shift":36},"real":{"Shift":19},"num":{"Shift":27},"unary":{"Shift":33},"factor":{"Shift":37},"id":{"Shift":16},"!":{"Shift":22},"false":{"Shift":28},"loc":{"Shift":23},"(":{"Shift":29},"term":{"Shift":46},"-":{"Shift":34}}},{"actions":{"/":{"Shift":41},"||":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"&&":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"<=":{"Reduce":{"left":"expr","right":["expr","+","term"]}},")":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"-":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"+":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"<":{"Reduce":{"left":"expr","right":["expr","+","term"]}},">=":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"==":{"Reduce":{"left":"expr","right":["expr","+","term"]}},";":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"!=":{"Reduce":{"left":"expr","right":["expr","+","term"]}},">":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"*":{"Shift":39}}},{"actions":{"&&":{"Reduce":{"left":"expr","right":["term"]}},";":{"Reduce":{"left":"expr","right":["term"]}},"!=":{"Reduce":{"left":"expr","right":["term"]}},"*":{"Shift":39},">=":{"Reduce":{"left":"expr","right":["term"]}},">":{"Reduce":{"left":"expr","right":["term"]}},")":{"Reduce":{"left":"expr","right":["term"]}},"||":{"Reduce":{"left":"expr","right":["term"]}},"==":{"Reduce":{"left":"expr","right":["term"]}},"-":{"Reduce":{"left":"expr","right":["term"]}},"/":{"Shift":41},"<":{"Reduce":{"left":"expr","right":["term"]}},"<=":{"Reduce":{"left":"expr","right":["term"]}},"+":{"Reduce":{"left":"expr","right":["term"]}}}},{"actions":{"num":{"Shift":27},"term":{"Shift":47},"unary":{"Shift":33},"real":{"Shift":19},"!":{"Shift":22},"(":{"Shift":29},"id":{"Shift":16},"expr":{"Shift":49},"false":{"Shift":28},"-":{"Shift":34},"factor":{"Shift":37},"true":{"Shift":36},"loc":{"Shift":23}}},{"actions":{"+":{"Shift":45},"==":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},"&&":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},";":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},")":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},"!=":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},"-":{"Shift":32},"||":{"Reduce":{"left":"rel","right":["expr",">","expr"]}}}},{"actions":{"factor":{"Shift":37},"true":{"Shift":36},"(":{"Shift":29},"-":{"Shift":34},"term":{"Shift":47},"real":{"Shift":19},"num":{"Shift":27},"loc":{"Shift":23},"id":{"Shift":16},"false":{"Shift":28},"unary":{"Shift":33},"expr":{"Shift":51},"!":{"Shift":22}}},{"actions":{"&&":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},";":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},"!=":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},"||":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},"+":{"Shift":45},")":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},"==":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},"-":{"Shift":32}}},{"actions":{"!":{"Shift":22},"true":{"Shift":36},"real":{"Shift":19},"unary":{"Shift":33},"expr":{"Shift":53},"factor":{"Shift":37},"-":{"Shift":34},"(":{"Shift":29},"term":{"Shift":47},"num":{"Shift":27},"loc":{"Shift":23},"false":{"Shift":28},"id":{"Shift":16}}},{"actions":{"&&":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},"+":{"Shift":45},"||":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},")":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},"==":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},"-":{"Shift":32},";":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},"!=":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}}}},{"actions":{")":{"Shift":55},"||":{"Shift":56}}},{"actions":{"-":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"<":{"Reduce":{"left":"factor","right":["(","bool",")"]}},">":{"Reduce":{"left":"factor","right":["(","bool",")"]}},">=":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"!=":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"/":{"Reduce":{"left":"factor","right":["(","bool",")"]}},")":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"==":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"&&":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"||":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"*":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"<=":{"Reduce":{"left":"factor","right":["(","bool",")"]}},";":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"+":{"Reduce":{"left":"factor","right":["(","bool",")"]}}}},{"actions":{"equality":{"Shift":20},"-":{"Shift":34},"expr":{"Shift":31},"join":{"Shift":57},"false":{"Shift":28},"loc":{"Shift":23},"unary":{"Shift":33},"id":{"Shift":16},"num":{"Shift":27},"true":{"Shift":36},"factor":{"Shift":37},"term":{"Shift":47},"!":{"Shift":22},"real":{"Shift":19},"(":{"Shift":29},"rel":{"Shift":30}}},{"actions":{"&&":{"Shift":58},";":{"Reduce":{"left":"bool","right":["bool","||","join"]}},"||":{"Reduce":{"left":"bool","right":["bool","||","join"]}},")":{"Reduce":{"left":"bool","right":["bool","||","join"]}}}},{"actions":{"factor":{"Shift":37},"-":{"Shift":34},"(":{"Shift":29},"expr":{"Shift":31},"unary":{"Shift":33},"num":{"Shift":27},"real":{"Shift":19},"equality":{"Shift":59},"false":{"Shift":28},"!":{"Shift":22},"id":{"Shift":16},"rel":{"Shift":30},"loc":{"Shift":23},"true":{"Shift":36},"term":{"Shift":47}}},{"actions":{"&&":{"Reduce":{"left":"join","right":["join","&&","equality"]}},"==":{"Shift":60},";":{"Reduce":{"left":"join","right":["join","&&","equality"]}},"!=":{"Shift":21},")":{"Reduce":{"left":"join","right":["join","&&","equality"]}},"||":{"Reduce":{"left":"join","right":["join","&&","equality"]}}}},{"actions":{"(":{"Shift":29},"true":{"Shift":36},"factor":{"Shift":37},"num":{"Shift":27},"real":{"Shift":19},"false":{"Shift":28},"-":{"Shift":34},"expr":{"Shift":31},"id":{"Shift":16},"term":{"Shift":47},"unary":{"Shift":33},"loc":{"Shift":23},"rel":{"Shift":61},"!":{"Shift":22}}},{"actions":{";":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},"!=":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},"==":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},")":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},"&&":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},"||":{"Reduce":{"left":"equality","right":["equality","==","rel"]}}}},{"actions":{"&&":{"Shift":58},";":{"Reduce":{"left":"bool","right":["join"]}},"||":{"Reduce":{"left":"bool","right":["join"]}},")":{"Reduce":{"left":"bool","right":["join"]}}}},{"actions":{"!=":{"Reduce":{"left":"unary","right":["!","unary"]}},"+":{"Reduce":{"left":"unary","right":["!","unary"]}},"/":{"Reduce":{"left":"unary","right":["!","unary"]}},")":{"Reduce":{"left":"unary","right":["!","unary"]}},"&&":{"Reduce":{"left":"unary","right":["!","unary"]}},"<":{"Reduce":{"left":"unary","right":["!","unary"]}},"<=":{"Reduce":{"left":"unary","right":["!","unary"]}},">":{"Reduce":{"left":"unary","right":["!","unary"]}},"||":{"Reduce":{"left":"unary","right":["!","unary"]}},"==":{"Reduce":{"left":"unary","right":["!","unary"]}},"-":{"Reduce":{"left":"unary","right":["!","unary"]}},";":{"Reduce":{"left":"unary","right":["!","unary"]}},">=":{"Reduce":{"left":"unary","right":["!","unary"]}},"*":{"Reduce":{"left":"unary","right":["!","unary"]}}}},{"actions":{")":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},";":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},"!=":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},"&&":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},"==":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},"||":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}}}},{"actions":{"||":{"Shift":56},")":{"Shift":66}}},{"actions":{"while":{"Shift":17},"loc":{"Shift":67},"if":{"Shift":72},"stmt":{"Shift":88},"block":{"Shift":71},"id":{"Shift":16},"break":{"Shift":76},"left_curly_brace":{"Shift":3},"do":{"Shift":78}}},{"actions":{"[":{"Shift":24},"=":{"Shift":68}}},{"actions":{"rel":{"Shift":30},"!":{"Shift":22},"true":{"Shift":36},"bool":{"Shift":69},"loc":{"Shift":23},"false":{"Shift":28},"expr":{"Shift":31},"factor":{"Shift":37},"-":{"Shift":34},"equality":{"Shift":20},"id":{"Shift":16},"real":{"Shift":19},"num":{"Shift":27},"(":{"Shift":29},"unary":{"Shift":33},"join":{"Shift":62},"term":{"Shift":47}}},{"actions":{";":{"Shift":70},"||":{"Shift":56}}},{"actions":{"else":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"break":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"id":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"do":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"while":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"if":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}}}},{"actions":{"while":{"Reduce":{"left":"stmt","right":["block"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["block"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["block"]}},"else":{"Reduce":{"left":"stmt","right":["block"]}},"id":{"Reduce":{"left":"stmt","right":["block"]}},"break":{"Reduce":{"left":"stmt","right":["block"]}},"do":{"Reduce":{"left":"stmt","right":["block"]}},"if":{"Reduce":{"left":"stmt","right":["block"]}}}},{"actions":{"(":{"Shift":73}}},{"actions":{"expr":{"Shift":31},"factor":{"Shift":37},"unary":{"Shift":33},"loc":{"Shift":23},"num":{"Shift":27},"true":{"Shift":36},"id":{"Shift":16},"!":{"Shift":22},"bool":{"Shift":74},"equality":{"Shift":20},"(":{"Shift":29},"false":{"Shift":28},"term":{"Shift":47},"-":{"Shift":34},"join":{"Shift":62},"rel":{"Shift":30},"real":{"Shift":19}}},{"actions":{"||":{"Shift":56},")":{"Shift":75}}},{"actions":{"left_curly_brace":{"Shift":3},"id":{"Shift":16},"loc":{"Shift":67},"block":{"Shift":71},"stmt":{"Shift":85},"break":{"Shift":76},"if":{"Shift":72},"while":{"Shift":17},"do":{"Shift":78}}},{"actions":{";":{"Shift":77}}},{"actions":{"if":{"Reduce":{"left":"stmt","right":["break",";"]}},"while":{"Reduce":{"left":"stmt","right":["break",";"]}},"else":{"Reduce":{"left":"stmt","right":["break",";"]}},"break":{"Reduce":{"left":"stmt","right":["break",";"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["break",";"]}},"id":{"Reduce":{"left":"stmt","right":["break",";"]}},"do":{"Reduce":{"left":"stmt","right":["break",";"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["break",";"]}}}},{"actions":{"do":{"Shift":78},"left_curly_brace":{"Shift":3},"stmt":{"Shift":79},"break":{"Shift":76},"block":{"Shift":71},"while":{"Shift":17},"id":{"Shift":16},"if":{"Shift":72},"loc":{"Shift":67}}},{"actions":{"while":{"Shift":80}}},{"actions":{"(":{"Shift":81}}},{"actions":{"id":{"Shift":16},"real":{"Shift":19},"(":{"Shift":29},"false":{"Shift":28},"expr":{"Shift":31},"factor":{"Shift":37},"!":{"Shift":22},"bool":{"Shift":82},"rel":{"Shift":30},"unary":{"Shift":33},"true":{"Shift":36},"term":{"Shift":47},"-":{"Shift":34},"loc":{"Shift":23},"num":{"Shift":27},"equality":{"Shift":20},"join":{"Shift":62}}},{"actions":{"||":{"Shift":56},")":{"Shift":83}}},{"actions":{";":{"Shift":84}}},{"actions":{"if":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"while":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"id":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"break":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"else":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"do":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}}}},{"actions":{"else":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"do":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"break":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"while":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"id":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"if":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}}}},{"actions":{"do":{"Shift":78},"loc":{"Shift":67},"block":{"Shift":71},"while":{"Shift":17},"break":{"Shift":76},"stmt":{"Shift":87},"left_curly_brace":{"Shift":3},"if":{"Shift":72},"id":{"Shift":16}}},{"actions":{"if":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"break":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"do":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"id":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"while":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"else":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}}}},{"actions":{"while":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"do":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"if":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"id":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"else":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"break":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}}}},{"actions":{"__$__":{"Reduce":{"left":"__DUMMY_START__","right":["S"]}}}}]}"#).unwrap();
        // ======================

        let mut handlers: HashMap<ReduceDerivation, Box<dyn Fn(Vec<String>) -> String>> =
            HashMap::new();

        // handlers generated by rparser
        // ======================
        handlers.insert(
            ReduceDerivation::build("S".into(), vec!["program".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("program".into(), vec!["block".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "block".into(),
                vec![
                    "left_curly_brace".into(),
                    "decls".into(),
                    "stmts".into(),
                    "right_curly_brace".into(),
                ],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("decls".into(), vec!["decls".into(), "decl".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("decls".into(), vec!["__EPSILON__".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("decl".into(), vec!["type".into(), "id".into(), ";".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "type".into(),
                vec!["type".into(), "[".into(), "num".into(), "]".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("type".into(), vec!["basic".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("stmts".into(), vec!["stmts".into(), "stmt".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("stmts".into(), vec!["__EPSILON__".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec!["loc".into(), "=".into(), "bool".into(), ";".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec![
                    "if".into(),
                    "(".into(),
                    "bool".into(),
                    ")".into(),
                    "stmt".into(),
                ],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec![
                    "if".into(),
                    "(".into(),
                    "bool".into(),
                    ")".into(),
                    "stmt".into(),
                    "else".into(),
                    "stmt".into(),
                ],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec![
                    "while".into(),
                    "(".into(),
                    "bool".into(),
                    ")".into(),
                    "stmt".into(),
                ],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec![
                    "do".into(),
                    "stmt".into(),
                    "while".into(),
                    "(".into(),
                    "bool".into(),
                    ")".into(),
                    ";".into(),
                ],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("stmt".into(), vec!["break".into(), ";".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("stmt".into(), vec!["block".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "loc".into(),
                vec!["loc".into(), "[".into(), "num".into(), "]".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("loc".into(), vec!["id".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "bool".into(),
                vec!["bool".into(), "||".into(), "join".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("bool".into(), vec!["join".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "join".into(),
                vec!["join".into(), "&&".into(), "equality".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("join".into(), vec!["equality".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "equality".into(),
                vec!["equality".into(), "==".into(), "rel".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "equality".into(),
                vec!["equality".into(), "!=".into(), "rel".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("equality".into(), vec!["rel".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("rel".into(), vec!["expr".into(), "<".into(), "expr".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "rel".into(),
                vec!["expr".into(), "<=".into(), "expr".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "rel".into(),
                vec!["expr".into(), ">=".into(), "expr".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("rel".into(), vec!["expr".into(), ">".into(), "expr".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("rel".into(), vec!["expr".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "expr".into(),
                vec!["expr".into(), "+".into(), "term".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "expr".into(),
                vec!["expr".into(), "-".into(), "term".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("expr".into(), vec!["term".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "term".into(),
                vec!["term".into(), "*".into(), "unary".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "term".into(),
                vec!["term".into(), "/".into(), "unary".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("term".into(), vec!["unary".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("unary".into(), vec!["!".into(), "unary".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("unary".into(), vec!["-".into(), "unary".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("unary".into(), vec!["factor".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["(".into(), "bool".into(), ")".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["loc".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["num".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["real".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["true".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["false".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        // ======================

        handlers.insert(
            ReduceDerivation::build(Self::DUMMY_START_SYMBOL.into(), vec!["S".into()]),
            Box::new(|vals| vals[0].clone()),
        );

        let mut res: RParser = RParser::default();
        res.action_table = action_table;
        res.handlers = handlers;
        res
    }

    // do shift-reduce parsing
    pub fn parse<T>(&self, tokens: Vec<T>) -> Result<ParsingTreeNode, Box<dyn Error>>
    where
        T: Token,
    {
        let mut shift_index = 0;
        let mut stack: Vec<NodePair> = Vec::new();

        stack.push(NodePair::new(
            ParsingTreeNode::build(Self::DUMMY_START_SYMBOL.into(), String::new(), Vec::new()),
            0,
        ));

        loop {
            let token_node = &tokens[shift_index].to_tree_node();

            let action = self
                .action_table
                .get_action(stack.last().unwrap().1, &token_node.symbol_type);

            match action {
                Some(Action::Shift(next_state)) => {
                    // shift
                    stack.push(NodePair::new(
                        tokens[shift_index].to_tree_node(),
                        *next_state,
                    ));
                    shift_index += 1;
                }
                Some(Action::Reduce(derivation)) => {
                    // pop right hand
                    let mut children: Vec<ParsingTreeNode> = Vec::new();
                    let mut datas = Vec::new();
                    for _ in 0..derivation.right.len() {
                        if let Some(top) = stack.pop() {
                            datas.push(top.0.data.clone());
                            children.push(top.0);
                        } else {
                            Err("parsing error: stack is empty.")?;
                        }
                    }

                    let children: Vec<_> = children.into_iter().rev().collect();
                    let datas: Vec<_> = datas.into_iter().rev().collect();
                    let handler = self.handlers.get(&derivation).unwrap();

                    // if the left hand side is dummy start symbol
                    // do nothing
                    if derivation.left == Self::DUMMY_START_SYMBOL {
                        stack.push(NodePair(
                            ParsingTreeNode::build(
                                derivation.left.to_string(),
                                handler(datas),
                                children,
                            ),
                            0,
                        ));
                        continue;
                    }

                    // goto[top_state(stack), X]
                    if let Action::Shift(next_state) = self
                        .action_table
                        .get_action(stack.last().unwrap().1, &derivation.left)
                        .unwrap()
                    {
                        stack.push(NodePair(
                            ParsingTreeNode::build(
                                derivation.left.to_string(),
                                handler(datas),
                                children,
                            ),
                            *next_state,
                        ));
                    } else {
                        Err("parsing error: invalid Shift action.")?;
                    }
                }
                Some(Action::Accept) => {
                    let res = stack.pop().unwrap().0;
                    return Ok(res);
                }
                _ => {
                    Err("parsing error: unknown.")?;
                }
            }
        }
    }
}
