use serde::{Deserialize, Serialize};
use std::{collections::HashMap, error::Error, hash::Hash};

// declarations
// ======================

pub struct Foo {
    x: i32,
    y: i32,
}

// ======================

/// Token
/// must implement Clone and Token trait
/// Token trait is used to convert a token to a tree node
pub trait Token: Clone {
    fn to_tree_node(&self) -> ParsingTreeNode;
}

pub struct ParsingTreeNode {
    pub symbol_type: String,
    pub data: String,
    pub children: Vec<ParsingTreeNode>,
}

impl ParsingTreeNode {
    pub fn build(symbol_type: String, data: String, children: Vec<ParsingTreeNode>) -> Self {
        ParsingTreeNode {
            symbol_type,
            data,
            children,
        }
    }
}

/// NodePair
/// a pair of a node and a state.
/// (TreeNode, state)
pub struct NodePair(ParsingTreeNode, usize);
impl NodePair {
    pub fn new(node: ParsingTreeNode, state: usize) -> Self {
        NodePair(node, state)
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ReduceDerivation {
    pub left: String,
    pub right: Vec<String>,
}

impl PartialEq for ReduceDerivation {
    fn eq(&self, other: &Self) -> bool {
        self.left == other.left && self.right == other.right
    }
}

impl Eq for ReduceDerivation {}

impl Hash for ReduceDerivation {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.left.hash(state);
        self.right.hash(state);
    }
}

impl ReduceDerivation {
    pub fn build(left: String, right: Vec<String>) -> Self {
        ReduceDerivation { left, right }
    }
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Action {
    Shift(usize),
    Reduce(ReduceDerivation),
    Accept,
    Error,
}

#[derive(Serialize, Deserialize)]
pub struct State {
    pub actions: HashMap<String, Action>,
}

impl State {
    pub fn new() -> Self {
        State {
            actions: HashMap::new(),
        }
    }
}

#[derive(Serialize, Deserialize, Default)]
pub struct ActionTable {
    pub states: Vec<State>,
}

impl ActionTable {
    pub fn get_action(&self, state: usize, symbol: &str) -> Option<&Action> {
        self.states[state].actions.get(symbol)
    }
}

#[derive(Default)]
pub struct RParser {
    action_table: ActionTable,
    handlers: HashMap<ReduceDerivation, Box<dyn Fn(Vec<String>) -> String>>,
    // variables
    // ======================
    pub a: i32,
    pub b: i64,
    // ======================
}

impl RParser {
    pub const END_SYMBOL: &'static str = "__$__";
    pub const EPSILON_SYMBOL: &'static str = "__EPSILON__";
    pub const DUMMY_START_SYMBOL: &'static str = "__DUMMY_START__";

    pub fn new() -> Self {
        // action table generated by rparser
        // ======================
        let action_table: ActionTable =  serde_json::from_str(r#"{"states":[{"actions":{"left_curly_brace":{"Shift":1},"program":{"Shift":90},"__$__":"Accept","block":{"Shift":88},"S":{"Shift":89}}},{"actions":{"stmts":{"Shift":87},"do":{"Shift":61},"decls":{"Shift":2},"id":{"Shift":12},"if":{"Shift":4},"break":{"Shift":58},"left_curly_brace":{"Shift":1},"block":{"Shift":60},"loc":{"Shift":62},"type":{"Shift":80},"while":{"Shift":66},"basic":{"Shift":79}}},{"actions":{"stmts":{"Shift":3},"basic":{"Shift":79},"left_curly_brace":{"Shift":1},"break":{"Shift":58},"block":{"Shift":60},"id":{"Shift":12},"type":{"Shift":80},"if":{"Shift":4},"do":{"Shift":61},"loc":{"Shift":62},"while":{"Shift":66},"decl":{"Shift":86}}},{"actions":{"left_curly_brace":{"Shift":1},"break":{"Shift":58},"loc":{"Shift":62},"if":{"Shift":4},"do":{"Shift":61},"while":{"Shift":66},"id":{"Shift":12},"block":{"Shift":60},"stmt":{"Shift":77},"right_curly_brace":{"Shift":78}}},{"actions":{"(":{"Shift":5}}},{"actions":{"bool":{"Shift":53},"factor":{"Shift":16},"term":{"Shift":14},"loc":{"Shift":18},"real":{"Shift":6},"-":{"Shift":7},"!":{"Shift":23},"expr":{"Shift":33},"unary":{"Shift":30},"(":{"Shift":9},"rel":{"Shift":13},"join":{"Shift":52},"num":{"Shift":10},"id":{"Shift":12},"false":{"Shift":22},"true":{"Shift":11},"equality":{"Shift":51}}},{"actions":{"<":{"Reduce":{"left":"factor","right":["real"]}},"/":{"Reduce":{"left":"factor","right":["real"]}},"||":{"Reduce":{"left":"factor","right":["real"]}},"==":{"Reduce":{"left":"factor","right":["real"]}},")":{"Reduce":{"left":"factor","right":["real"]}},">=":{"Reduce":{"left":"factor","right":["real"]}},"&&":{"Reduce":{"left":"factor","right":["real"]}},"-":{"Reduce":{"left":"factor","right":["real"]}},"!=":{"Reduce":{"left":"factor","right":["real"]}},"*":{"Reduce":{"left":"factor","right":["real"]}},">":{"Reduce":{"left":"factor","right":["real"]}},";":{"Reduce":{"left":"factor","right":["real"]}},"+":{"Reduce":{"left":"factor","right":["real"]}},"<=":{"Reduce":{"left":"factor","right":["real"]}}}},{"actions":{"!":{"Shift":23},"factor":{"Shift":16},"unary":{"Shift":8},"false":{"Shift":22},"id":{"Shift":12},"true":{"Shift":11},"(":{"Shift":9},"num":{"Shift":10},"real":{"Shift":6},"loc":{"Shift":18},"-":{"Shift":7}}},{"actions":{"*":{"Reduce":{"left":"unary","right":["-","unary"]}},"||":{"Reduce":{"left":"unary","right":["-","unary"]}},"<=":{"Reduce":{"left":"unary","right":["-","unary"]}},")":{"Reduce":{"left":"unary","right":["-","unary"]}},"!=":{"Reduce":{"left":"unary","right":["-","unary"]}},">":{"Reduce":{"left":"unary","right":["-","unary"]}},"<":{"Reduce":{"left":"unary","right":["-","unary"]}},"==":{"Reduce":{"left":"unary","right":["-","unary"]}},"/":{"Reduce":{"left":"unary","right":["-","unary"]}},"+":{"Reduce":{"left":"unary","right":["-","unary"]}},"&&":{"Reduce":{"left":"unary","right":["-","unary"]}},">=":{"Reduce":{"left":"unary","right":["-","unary"]}},";":{"Reduce":{"left":"unary","right":["-","unary"]}},"-":{"Reduce":{"left":"unary","right":["-","unary"]}}}},{"actions":{"false":{"Shift":22},"num":{"Shift":10},"factor":{"Shift":16},"expr":{"Shift":33},"bool":{"Shift":27},"unary":{"Shift":30},"rel":{"Shift":13},"(":{"Shift":9},"term":{"Shift":14},"real":{"Shift":6},"id":{"Shift":12},"equality":{"Shift":51},"join":{"Shift":52},"true":{"Shift":11},"!":{"Shift":23},"-":{"Shift":7},"loc":{"Shift":18}}},{"actions":{"!=":{"Reduce":{"left":"factor","right":["num"]}},"<":{"Reduce":{"left":"factor","right":["num"]}},"/":{"Reduce":{"left":"factor","right":["num"]}},">":{"Reduce":{"left":"factor","right":["num"]}},"&&":{"Reduce":{"left":"factor","right":["num"]}},"*":{"Reduce":{"left":"factor","right":["num"]}},"==":{"Reduce":{"left":"factor","right":["num"]}},";":{"Reduce":{"left":"factor","right":["num"]}},"||":{"Reduce":{"left":"factor","right":["num"]}},"-":{"Reduce":{"left":"factor","right":["num"]}},"+":{"Reduce":{"left":"factor","right":["num"]}},")":{"Reduce":{"left":"factor","right":["num"]}},"<=":{"Reduce":{"left":"factor","right":["num"]}},">=":{"Reduce":{"left":"factor","right":["num"]}}}},{"actions":{"!=":{"Reduce":{"left":"factor","right":["true"]}},">":{"Reduce":{"left":"factor","right":["true"]}},"+":{"Reduce":{"left":"factor","right":["true"]}},"&&":{"Reduce":{"left":"factor","right":["true"]}},"<=":{"Reduce":{"left":"factor","right":["true"]}},">=":{"Reduce":{"left":"factor","right":["true"]}},")":{"Reduce":{"left":"factor","right":["true"]}},";":{"Reduce":{"left":"factor","right":["true"]}},"-":{"Reduce":{"left":"factor","right":["true"]}},"<":{"Reduce":{"left":"factor","right":["true"]}},"==":{"Reduce":{"left":"factor","right":["true"]}},"/":{"Reduce":{"left":"factor","right":["true"]}},"||":{"Reduce":{"left":"factor","right":["true"]}},"*":{"Reduce":{"left":"factor","right":["true"]}}}},{"actions":{"/":{"Reduce":{"left":"loc","right":["id"]}},"||":{"Reduce":{"left":"loc","right":["id"]}},"[":{"Reduce":{"left":"loc","right":["id"]}},")":{"Reduce":{"left":"loc","right":["id"]}},"-":{"Reduce":{"left":"loc","right":["id"]}},"<":{"Reduce":{"left":"loc","right":["id"]}},";":{"Reduce":{"left":"loc","right":["id"]}},"==":{"Reduce":{"left":"loc","right":["id"]}},"*":{"Reduce":{"left":"loc","right":["id"]}},"&&":{"Reduce":{"left":"loc","right":["id"]}},">=":{"Reduce":{"left":"loc","right":["id"]}},"=":{"Reduce":{"left":"loc","right":["id"]}},"!=":{"Reduce":{"left":"loc","right":["id"]}},"+":{"Reduce":{"left":"loc","right":["id"]}},"<=":{"Reduce":{"left":"loc","right":["id"]}},">":{"Reduce":{"left":"loc","right":["id"]}}}},{"actions":{")":{"Reduce":{"left":"equality","right":["rel"]}},"||":{"Reduce":{"left":"equality","right":["rel"]}},"==":{"Reduce":{"left":"equality","right":["rel"]}},"!=":{"Reduce":{"left":"equality","right":["rel"]}},"&&":{"Reduce":{"left":"equality","right":["rel"]}},";":{"Reduce":{"left":"equality","right":["rel"]}}}},{"actions":{"==":{"Reduce":{"left":"expr","right":["term"]}},")":{"Reduce":{"left":"expr","right":["term"]}},"+":{"Reduce":{"left":"expr","right":["term"]}},"*":{"Shift":25},"<=":{"Reduce":{"left":"expr","right":["term"]}},">=":{"Reduce":{"left":"expr","right":["term"]}},"-":{"Reduce":{"left":"expr","right":["term"]}},"!=":{"Reduce":{"left":"expr","right":["term"]}},"/":{"Shift":15},"||":{"Reduce":{"left":"expr","right":["term"]}},">":{"Reduce":{"left":"expr","right":["term"]}},"<":{"Reduce":{"left":"expr","right":["term"]}},"&&":{"Reduce":{"left":"expr","right":["term"]}},";":{"Reduce":{"left":"expr","right":["term"]}}}},{"actions":{"factor":{"Shift":16},"unary":{"Shift":17},"real":{"Shift":6},"!":{"Shift":23},"id":{"Shift":12},"true":{"Shift":11},"loc":{"Shift":18},"-":{"Shift":7},"(":{"Shift":9},"num":{"Shift":10},"false":{"Shift":22}}},{"actions":{">=":{"Reduce":{"left":"unary","right":["factor"]}},">":{"Reduce":{"left":"unary","right":["factor"]}},")":{"Reduce":{"left":"unary","right":["factor"]}},"!=":{"Reduce":{"left":"unary","right":["factor"]}},"+":{"Reduce":{"left":"unary","right":["factor"]}},"<=":{"Reduce":{"left":"unary","right":["factor"]}},"&&":{"Reduce":{"left":"unary","right":["factor"]}},";":{"Reduce":{"left":"unary","right":["factor"]}},"/":{"Reduce":{"left":"unary","right":["factor"]}},"==":{"Reduce":{"left":"unary","right":["factor"]}},"<":{"Reduce":{"left":"unary","right":["factor"]}},"*":{"Reduce":{"left":"unary","right":["factor"]}},"-":{"Reduce":{"left":"unary","right":["factor"]}},"||":{"Reduce":{"left":"unary","right":["factor"]}}}},{"actions":{">":{"Reduce":{"left":"term","right":["term","/","unary"]}},"/":{"Reduce":{"left":"term","right":["term","/","unary"]}},"*":{"Reduce":{"left":"term","right":["term","/","unary"]}},")":{"Reduce":{"left":"term","right":["term","/","unary"]}},"-":{"Reduce":{"left":"term","right":["term","/","unary"]}},"<":{"Reduce":{"left":"term","right":["term","/","unary"]}},"&&":{"Reduce":{"left":"term","right":["term","/","unary"]}},"||":{"Reduce":{"left":"term","right":["term","/","unary"]}},"!=":{"Reduce":{"left":"term","right":["term","/","unary"]}},";":{"Reduce":{"left":"term","right":["term","/","unary"]}},"<=":{"Reduce":{"left":"term","right":["term","/","unary"]}},"+":{"Reduce":{"left":"term","right":["term","/","unary"]}},">=":{"Reduce":{"left":"term","right":["term","/","unary"]}},"==":{"Reduce":{"left":"term","right":["term","/","unary"]}}}},{"actions":{"[":{"Shift":19},">=":{"Reduce":{"left":"factor","right":["loc"]}},">":{"Reduce":{"left":"factor","right":["loc"]}},")":{"Reduce":{"left":"factor","right":["loc"]}},"==":{"Reduce":{"left":"factor","right":["loc"]}},"<=":{"Reduce":{"left":"factor","right":["loc"]}},"!=":{"Reduce":{"left":"factor","right":["loc"]}},"*":{"Reduce":{"left":"factor","right":["loc"]}},"&&":{"Reduce":{"left":"factor","right":["loc"]}},"-":{"Reduce":{"left":"factor","right":["loc"]}},"+":{"Reduce":{"left":"factor","right":["loc"]}},"<":{"Reduce":{"left":"factor","right":["loc"]}},"||":{"Reduce":{"left":"factor","right":["loc"]}},";":{"Reduce":{"left":"factor","right":["loc"]}},"/":{"Reduce":{"left":"factor","right":["loc"]}}}},{"actions":{"num":{"Shift":20}}},{"actions":{"]":{"Shift":21}}},{"actions":{">":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},";":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"*":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"!=":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"&&":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"[":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"<":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},">=":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"||":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"<=":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"+":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"=":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"-":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"/":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},")":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"==":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}}}},{"actions":{")":{"Reduce":{"left":"factor","right":["false"]}},"&&":{"Reduce":{"left":"factor","right":["false"]}},"<=":{"Reduce":{"left":"factor","right":["false"]}},";":{"Reduce":{"left":"factor","right":["false"]}},"<":{"Reduce":{"left":"factor","right":["false"]}},">":{"Reduce":{"left":"factor","right":["false"]}},"/":{"Reduce":{"left":"factor","right":["false"]}},"||":{"Reduce":{"left":"factor","right":["false"]}},"-":{"Reduce":{"left":"factor","right":["false"]}},"==":{"Reduce":{"left":"factor","right":["false"]}},"!=":{"Reduce":{"left":"factor","right":["false"]}},">=":{"Reduce":{"left":"factor","right":["false"]}},"*":{"Reduce":{"left":"factor","right":["false"]}},"+":{"Reduce":{"left":"factor","right":["false"]}}}},{"actions":{"!":{"Shift":23},"-":{"Shift":7},"false":{"Shift":22},"loc":{"Shift":18},"true":{"Shift":11},"id":{"Shift":12},"(":{"Shift":9},"real":{"Shift":6},"factor":{"Shift":16},"num":{"Shift":10},"unary":{"Shift":24}}},{"actions":{"||":{"Reduce":{"left":"unary","right":["!","unary"]}},"+":{"Reduce":{"left":"unary","right":["!","unary"]}},"<=":{"Reduce":{"left":"unary","right":["!","unary"]}},")":{"Reduce":{"left":"unary","right":["!","unary"]}},">=":{"Reduce":{"left":"unary","right":["!","unary"]}},"&&":{"Reduce":{"left":"unary","right":["!","unary"]}},"!=":{"Reduce":{"left":"unary","right":["!","unary"]}},";":{"Reduce":{"left":"unary","right":["!","unary"]}},">":{"Reduce":{"left":"unary","right":["!","unary"]}},"*":{"Reduce":{"left":"unary","right":["!","unary"]}},"<":{"Reduce":{"left":"unary","right":["!","unary"]}},"-":{"Reduce":{"left":"unary","right":["!","unary"]}},"/":{"Reduce":{"left":"unary","right":["!","unary"]}},"==":{"Reduce":{"left":"unary","right":["!","unary"]}}}},{"actions":{"factor":{"Shift":16},"!":{"Shift":23},"(":{"Shift":9},"true":{"Shift":11},"unary":{"Shift":26},"real":{"Shift":6},"loc":{"Shift":18},"id":{"Shift":12},"false":{"Shift":22},"num":{"Shift":10},"-":{"Shift":7}}},{"actions":{"!=":{"Reduce":{"left":"term","right":["term","*","unary"]}},"||":{"Reduce":{"left":"term","right":["term","*","unary"]}},"<":{"Reduce":{"left":"term","right":["term","*","unary"]}},")":{"Reduce":{"left":"term","right":["term","*","unary"]}},">=":{"Reduce":{"left":"term","right":["term","*","unary"]}},"==":{"Reduce":{"left":"term","right":["term","*","unary"]}},"/":{"Reduce":{"left":"term","right":["term","*","unary"]}},"<=":{"Reduce":{"left":"term","right":["term","*","unary"]}},"&&":{"Reduce":{"left":"term","right":["term","*","unary"]}},"*":{"Reduce":{"left":"term","right":["term","*","unary"]}},"+":{"Reduce":{"left":"term","right":["term","*","unary"]}},";":{"Reduce":{"left":"term","right":["term","*","unary"]}},">":{"Reduce":{"left":"term","right":["term","*","unary"]}},"-":{"Reduce":{"left":"term","right":["term","*","unary"]}}}},{"actions":{")":{"Shift":28},"||":{"Shift":29}}},{"actions":{";":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"/":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"!=":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"==":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"<=":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"<":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"&&":{"Reduce":{"left":"factor","right":["(","bool",")"]}},")":{"Reduce":{"left":"factor","right":["(","bool",")"]}},">":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"+":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"-":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"*":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"||":{"Reduce":{"left":"factor","right":["(","bool",")"]}},">=":{"Reduce":{"left":"factor","right":["(","bool",")"]}}}},{"actions":{"join":{"Shift":31},"term":{"Shift":14},"-":{"Shift":7},"loc":{"Shift":18},"true":{"Shift":11},"rel":{"Shift":13},"id":{"Shift":12},"(":{"Shift":9},"equality":{"Shift":51},"false":{"Shift":22},"expr":{"Shift":33},"!":{"Shift":23},"num":{"Shift":10},"unary":{"Shift":30},"factor":{"Shift":16},"real":{"Shift":6}}},{"actions":{">=":{"Reduce":{"left":"term","right":["unary"]}},")":{"Reduce":{"left":"term","right":["unary"]}},"/":{"Reduce":{"left":"term","right":["unary"]}},"*":{"Reduce":{"left":"term","right":["unary"]}},";":{"Reduce":{"left":"term","right":["unary"]}},"<=":{"Reduce":{"left":"term","right":["unary"]}},"==":{"Reduce":{"left":"term","right":["unary"]}},">":{"Reduce":{"left":"term","right":["unary"]}},"<":{"Reduce":{"left":"term","right":["unary"]}},"!=":{"Reduce":{"left":"term","right":["unary"]}},"-":{"Reduce":{"left":"term","right":["unary"]}},"||":{"Reduce":{"left":"term","right":["unary"]}},"+":{"Reduce":{"left":"term","right":["unary"]}},"&&":{"Reduce":{"left":"term","right":["unary"]}}}},{"actions":{")":{"Reduce":{"left":"bool","right":["bool","||","join"]}},"&&":{"Shift":32},";":{"Reduce":{"left":"bool","right":["bool","||","join"]}},"||":{"Reduce":{"left":"bool","right":["bool","||","join"]}}}},{"actions":{"rel":{"Shift":13},"true":{"Shift":11},"term":{"Shift":14},"real":{"Shift":6},"false":{"Shift":22},"unary":{"Shift":30},"!":{"Shift":23},"num":{"Shift":10},"loc":{"Shift":18},"equality":{"Shift":46},"-":{"Shift":7},"(":{"Shift":9},"id":{"Shift":12},"expr":{"Shift":33},"factor":{"Shift":16}}},{"actions":{"+":{"Shift":38},"||":{"Reduce":{"left":"rel","right":["expr"]}},">":{"Shift":42},"<=":{"Shift":40},"<":{"Shift":34},"==":{"Reduce":{"left":"rel","right":["expr"]}},"!=":{"Reduce":{"left":"rel","right":["expr"]}},")":{"Reduce":{"left":"rel","right":["expr"]}},"&&":{"Reduce":{"left":"rel","right":["expr"]}},";":{"Reduce":{"left":"rel","right":["expr"]}},">=":{"Shift":44},"-":{"Shift":36}}},{"actions":{"real":{"Shift":6},"true":{"Shift":11},"!":{"Shift":23},"term":{"Shift":14},"expr":{"Shift":35},"loc":{"Shift":18},"(":{"Shift":9},"id":{"Shift":12},"factor":{"Shift":16},"num":{"Shift":10},"false":{"Shift":22},"unary":{"Shift":30},"-":{"Shift":7}}},{"actions":{"!=":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},"-":{"Shift":36},";":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},"+":{"Shift":38},"==":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},")":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},"&&":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},"||":{"Reduce":{"left":"rel","right":["expr","<","expr"]}}}},{"actions":{"!":{"Shift":23},"false":{"Shift":22},"term":{"Shift":37},"(":{"Shift":9},"factor":{"Shift":16},"unary":{"Shift":30},"-":{"Shift":7},"num":{"Shift":10},"true":{"Shift":11},"id":{"Shift":12},"loc":{"Shift":18},"real":{"Shift":6}}},{"actions":{"&&":{"Reduce":{"left":"expr","right":["expr","-","term"]}},";":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"+":{"Reduce":{"left":"expr","right":["expr","-","term"]}},">":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"*":{"Shift":25},"/":{"Shift":15},")":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"<=":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"!=":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"==":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"-":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"<":{"Reduce":{"left":"expr","right":["expr","-","term"]}},">=":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"||":{"Reduce":{"left":"expr","right":["expr","-","term"]}}}},{"actions":{"id":{"Shift":12},"loc":{"Shift":18},"term":{"Shift":39},"factor":{"Shift":16},"num":{"Shift":10},"unary":{"Shift":30},"-":{"Shift":7},"true":{"Shift":11},"(":{"Shift":9},"real":{"Shift":6},"false":{"Shift":22},"!":{"Shift":23}}},{"actions":{"==":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"<":{"Reduce":{"left":"expr","right":["expr","+","term"]}},">=":{"Reduce":{"left":"expr","right":["expr","+","term"]}},")":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"*":{"Shift":25},"&&":{"Reduce":{"left":"expr","right":["expr","+","term"]}},";":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"/":{"Shift":15},"+":{"Reduce":{"left":"expr","right":["expr","+","term"]}},">":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"||":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"<=":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"-":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"!=":{"Reduce":{"left":"expr","right":["expr","+","term"]}}}},{"actions":{"num":{"Shift":10},"id":{"Shift":12},"true":{"Shift":11},"factor":{"Shift":16},"(":{"Shift":9},"!":{"Shift":23},"false":{"Shift":22},"term":{"Shift":14},"expr":{"Shift":41},"real":{"Shift":6},"loc":{"Shift":18},"unary":{"Shift":30},"-":{"Shift":7}}},{"actions":{"-":{"Shift":36},"+":{"Shift":38},")":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},";":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},"==":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},"||":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},"!=":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},"&&":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}}}},{"actions":{"expr":{"Shift":43},"(":{"Shift":9},"real":{"Shift":6},"num":{"Shift":10},"factor":{"Shift":16},"id":{"Shift":12},"loc":{"Shift":18},"unary":{"Shift":30},"false":{"Shift":22},"true":{"Shift":11},"-":{"Shift":7},"term":{"Shift":14},"!":{"Shift":23}}},{"actions":{")":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},"+":{"Shift":38},"!=":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},"||":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},"-":{"Shift":36},";":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},"&&":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},"==":{"Reduce":{"left":"rel","right":["expr",">","expr"]}}}},{"actions":{"real":{"Shift":6},"-":{"Shift":7},"factor":{"Shift":16},"unary":{"Shift":30},"term":{"Shift":14},"(":{"Shift":9},"true":{"Shift":11},"expr":{"Shift":45},"id":{"Shift":12},"false":{"Shift":22},"loc":{"Shift":18},"!":{"Shift":23},"num":{"Shift":10}}},{"actions":{";":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},"!=":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},"-":{"Shift":36},"&&":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},"||":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},")":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},"==":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},"+":{"Shift":38}}},{"actions":{"&&":{"Reduce":{"left":"join","right":["join","&&","equality"]}},"!=":{"Shift":47},")":{"Reduce":{"left":"join","right":["join","&&","equality"]}},"==":{"Shift":49},";":{"Reduce":{"left":"join","right":["join","&&","equality"]}},"||":{"Reduce":{"left":"join","right":["join","&&","equality"]}}}},{"actions":{"expr":{"Shift":33},"true":{"Shift":11},"(":{"Shift":9},"real":{"Shift":6},"-":{"Shift":7},"factor":{"Shift":16},"id":{"Shift":12},"num":{"Shift":10},"term":{"Shift":14},"!":{"Shift":23},"loc":{"Shift":18},"rel":{"Shift":48},"unary":{"Shift":30},"false":{"Shift":22}}},{"actions":{"||":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},"&&":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},"==":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},";":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},"!=":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},")":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}}}},{"actions":{"num":{"Shift":10},"term":{"Shift":14},"!":{"Shift":23},"factor":{"Shift":16},"real":{"Shift":6},"id":{"Shift":12},"false":{"Shift":22},"unary":{"Shift":30},"loc":{"Shift":18},"expr":{"Shift":33},"true":{"Shift":11},"rel":{"Shift":50},"(":{"Shift":9},"-":{"Shift":7}}},{"actions":{"!=":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},"&&":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},"==":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},"||":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},";":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},")":{"Reduce":{"left":"equality","right":["equality","==","rel"]}}}},{"actions":{"==":{"Shift":49},"!=":{"Shift":47},"&&":{"Reduce":{"left":"join","right":["equality"]}},")":{"Reduce":{"left":"join","right":["equality"]}},";":{"Reduce":{"left":"join","right":["equality"]}},"||":{"Reduce":{"left":"join","right":["equality"]}}}},{"actions":{"||":{"Reduce":{"left":"bool","right":["join"]}},")":{"Reduce":{"left":"bool","right":["join"]}},"&&":{"Shift":32},";":{"Reduce":{"left":"bool","right":["join"]}}}},{"actions":{")":{"Shift":54},"||":{"Shift":29}}},{"actions":{"break":{"Shift":58},"id":{"Shift":12},"while":{"Shift":66},"do":{"Shift":61},"block":{"Shift":60},"if":{"Shift":4},"stmt":{"Shift":55},"loc":{"Shift":62},"left_curly_brace":{"Shift":1}}},{"actions":{"right_curly_brace":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"if":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"id":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"else":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"break":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"while":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"do":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}}}},{"actions":{"left_curly_brace":{"Shift":1},"block":{"Shift":60},"if":{"Shift":4},"while":{"Shift":66},"break":{"Shift":58},"loc":{"Shift":62},"do":{"Shift":61},"stmt":{"Shift":57},"id":{"Shift":12}}},{"actions":{"right_curly_brace":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"if":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"else":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"while":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"do":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"id":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"break":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}}}},{"actions":{";":{"Shift":59}}},{"actions":{"if":{"Reduce":{"left":"stmt","right":["break",";"]}},"do":{"Reduce":{"left":"stmt","right":["break",";"]}},"break":{"Reduce":{"left":"stmt","right":["break",";"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["break",";"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["break",";"]}},"id":{"Reduce":{"left":"stmt","right":["break",";"]}},"else":{"Reduce":{"left":"stmt","right":["break",";"]}},"while":{"Reduce":{"left":"stmt","right":["break",";"]}}}},{"actions":{"right_curly_brace":{"Reduce":{"left":"stmt","right":["block"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["block"]}},"else":{"Reduce":{"left":"stmt","right":["block"]}},"do":{"Reduce":{"left":"stmt","right":["block"]}},"break":{"Reduce":{"left":"stmt","right":["block"]}},"if":{"Reduce":{"left":"stmt","right":["block"]}},"while":{"Reduce":{"left":"stmt","right":["block"]}},"id":{"Reduce":{"left":"stmt","right":["block"]}}}},{"actions":{"break":{"Shift":58},"loc":{"Shift":62},"do":{"Shift":61},"if":{"Shift":4},"left_curly_brace":{"Shift":1},"stmt":{"Shift":71},"block":{"Shift":60},"id":{"Shift":12},"while":{"Shift":66}}},{"actions":{"[":{"Shift":19},"=":{"Shift":63}}},{"actions":{"!":{"Shift":23},"loc":{"Shift":18},"rel":{"Shift":13},"factor":{"Shift":16},"expr":{"Shift":33},"join":{"Shift":52},"id":{"Shift":12},"-":{"Shift":7},"equality":{"Shift":51},"false":{"Shift":22},"unary":{"Shift":30},"true":{"Shift":11},"bool":{"Shift":64},"num":{"Shift":10},"real":{"Shift":6},"term":{"Shift":14},"(":{"Shift":9}}},{"actions":{";":{"Shift":65},"||":{"Shift":29}}},{"actions":{"if":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"while":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"break":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"id":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"do":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"else":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}}}},{"actions":{"(":{"Shift":67}}},{"actions":{"loc":{"Shift":18},"expr":{"Shift":33},"real":{"Shift":6},"unary":{"Shift":30},"join":{"Shift":52},"id":{"Shift":12},"rel":{"Shift":13},"equality":{"Shift":51},"true":{"Shift":11},"-":{"Shift":7},"factor":{"Shift":16},"num":{"Shift":10},"term":{"Shift":14},"false":{"Shift":22},"!":{"Shift":23},"(":{"Shift":9},"bool":{"Shift":68}}},{"actions":{"||":{"Shift":29},")":{"Shift":69}}},{"actions":{"if":{"Shift":4},"left_curly_brace":{"Shift":1},"while":{"Shift":66},"break":{"Shift":58},"do":{"Shift":61},"block":{"Shift":60},"id":{"Shift":12},"stmt":{"Shift":70},"loc":{"Shift":62}}},{"actions":{"right_curly_brace":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"else":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"id":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"while":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"break":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"do":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"if":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}}}},{"actions":{"while":{"Shift":72}}},{"actions":{"(":{"Shift":73}}},{"actions":{"id":{"Shift":12},"term":{"Shift":14},"join":{"Shift":52},"num":{"Shift":10},"!":{"Shift":23},"factor":{"Shift":16},"unary":{"Shift":30},"expr":{"Shift":33},"loc":{"Shift":18},"real":{"Shift":6},"-":{"Shift":7},"false":{"Shift":22},"true":{"Shift":11},"equality":{"Shift":51},"rel":{"Shift":13},"bool":{"Shift":74},"(":{"Shift":9}}},{"actions":{")":{"Shift":75},"||":{"Shift":29}}},{"actions":{";":{"Shift":76}}},{"actions":{"left_curly_brace":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"if":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"else":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"while":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"do":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"id":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"break":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}}}},{"actions":{"if":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"break":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"left_curly_brace":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"right_curly_brace":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"while":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"do":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"id":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}}}},{"actions":{"left_curly_brace":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"else":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"while":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"__$__":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"if":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"right_curly_brace":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"break":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"id":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"do":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}}}},{"actions":{"id":{"Reduce":{"left":"type","right":["basic"]}},"[":{"Reduce":{"left":"type","right":["basic"]}}}},{"actions":{"[":{"Shift":83},"id":{"Shift":81}}},{"actions":{";":{"Shift":82}}},{"actions":{"left_curly_brace":{"Reduce":{"left":"decl","right":["type","id",";"]}},"do":{"Reduce":{"left":"decl","right":["type","id",";"]}},"id":{"Reduce":{"left":"decl","right":["type","id",";"]}},"while":{"Reduce":{"left":"decl","right":["type","id",";"]}},"if":{"Reduce":{"left":"decl","right":["type","id",";"]}},"break":{"Reduce":{"left":"decl","right":["type","id",";"]}},"basic":{"Reduce":{"left":"decl","right":["type","id",";"]}}}},{"actions":{"num":{"Shift":84}}},{"actions":{"]":{"Shift":85}}},{"actions":{"id":{"Reduce":{"left":"type","right":["type","[","num","]"]}},"[":{"Reduce":{"left":"type","right":["type","[","num","]"]}}}},{"actions":{"basic":{"Reduce":{"left":"decls","right":["decls","decl"]}},"break":{"Reduce":{"left":"decls","right":["decls","decl"]}},"while":{"Reduce":{"left":"decls","right":["decls","decl"]}},"left_curly_brace":{"Reduce":{"left":"decls","right":["decls","decl"]}},"do":{"Reduce":{"left":"decls","right":["decls","decl"]}},"id":{"Reduce":{"left":"decls","right":["decls","decl"]}},"if":{"Reduce":{"left":"decls","right":["decls","decl"]}}}},{"actions":{"break":{"Shift":58},"id":{"Shift":12},"stmt":{"Shift":77},"if":{"Shift":4},"loc":{"Shift":62},"block":{"Shift":60},"do":{"Shift":61},"while":{"Shift":66},"left_curly_brace":{"Shift":1}}},{"actions":{"__$__":{"Reduce":{"left":"program","right":["block"]}}}},{"actions":{"__$__":{"Reduce":{"left":"__DUMMY_START__","right":["S"]}}}},{"actions":{"__$__":{"Reduce":{"left":"S","right":["program"]}}}}]}"#).unwrap();
        // ======================

        let mut handlers: HashMap<ReduceDerivation, Box<dyn Fn(Vec<String>) -> String>> =
            HashMap::new();

        // handlers generated by rparser
        // ======================
        handlers.insert(
            ReduceDerivation::build("S".into(), vec!["program".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("program".into(), vec!["block".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "block".into(),
                vec![
                    "left_curly_brace".into(),
                    "decls".into(),
                    "stmts".into(),
                    "right_curly_brace".into(),
                ],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("decls".into(), vec!["decls".into(), "decl".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("decls".into(), vec!["__EPSILON__".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("decl".into(), vec!["type".into(), "id".into(), ";".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "type".into(),
                vec!["type".into(), "[".into(), "num".into(), "]".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("type".into(), vec!["basic".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("stmts".into(), vec!["stmts".into(), "stmt".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("stmts".into(), vec!["__EPSILON__".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec!["loc".into(), "=".into(), "bool".into(), ";".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec![
                    "if".into(),
                    "(".into(),
                    "bool".into(),
                    ")".into(),
                    "stmt".into(),
                ],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec![
                    "if".into(),
                    "(".into(),
                    "bool".into(),
                    ")".into(),
                    "stmt".into(),
                    "else".into(),
                    "stmt".into(),
                ],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec![
                    "while".into(),
                    "(".into(),
                    "bool".into(),
                    ")".into(),
                    "stmt".into(),
                ],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec![
                    "do".into(),
                    "stmt".into(),
                    "while".into(),
                    "(".into(),
                    "bool".into(),
                    ")".into(),
                    ";".into(),
                ],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("stmt".into(), vec!["break".into(), ";".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("stmt".into(), vec!["block".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "loc".into(),
                vec!["loc".into(), "[".into(), "num".into(), "]".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("loc".into(), vec!["id".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "bool".into(),
                vec!["bool".into(), "||".into(), "join".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("bool".into(), vec!["join".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "join".into(),
                vec!["join".into(), "&&".into(), "equality".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("join".into(), vec!["equality".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "equality".into(),
                vec!["equality".into(), "==".into(), "rel".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "equality".into(),
                vec!["equality".into(), "!=".into(), "rel".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("equality".into(), vec!["rel".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("rel".into(), vec!["expr".into(), "<".into(), "expr".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "rel".into(),
                vec!["expr".into(), "<=".into(), "expr".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "rel".into(),
                vec!["expr".into(), ">=".into(), "expr".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("rel".into(), vec!["expr".into(), ">".into(), "expr".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("rel".into(), vec!["expr".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "expr".into(),
                vec!["expr".into(), "+".into(), "term".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "expr".into(),
                vec!["expr".into(), "-".into(), "term".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("expr".into(), vec!["term".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "term".into(),
                vec!["term".into(), "*".into(), "unary".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build(
                "term".into(),
                vec!["term".into(), "/".into(), "unary".into()],
            ),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("term".into(), vec!["unary".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("unary".into(), vec!["!".into(), "unary".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("unary".into(), vec!["-".into(), "unary".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("unary".into(), vec!["factor".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["(".into(), "bool".into(), ")".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["loc".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["num".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["real".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["true".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["false".into()]),
            Box::new(|datas| datas[0].clone()),
        );
        // ======================

        handlers.insert(
            ReduceDerivation::build(Self::DUMMY_START_SYMBOL.into(), vec!["S".into()]),
            Box::new(|vals| vals[0].clone()),
        );

        let mut res: RParser = RParser::default();
        res.action_table = action_table;
        res.handlers = handlers;
        res
    }

    // do shift-reduce parsing
    pub fn parse<T>(&self, tokens: Vec<T>) -> Result<ParsingTreeNode, Box<dyn Error>>
    where
        T: Token,
    {
        let mut shift_index = 0;
        let mut stack: Vec<NodePair> = Vec::new();

        stack.push(NodePair::new(
            ParsingTreeNode::build(Self::DUMMY_START_SYMBOL.into(), String::new(), Vec::new()),
            0,
        ));

        loop {
            let token_node = &tokens[shift_index].to_tree_node();

            let action = self
                .action_table
                .get_action(stack.last().unwrap().1, &token_node.symbol_type);

            match action {
                Some(Action::Shift(next_state)) => {
                    // shift
                    stack.push(NodePair::new(
                        tokens[shift_index].to_tree_node(),
                        *next_state,
                    ));
                    shift_index += 1;
                }
                Some(Action::Reduce(derivation)) => {
                    // pop right hand
                    let mut children: Vec<ParsingTreeNode> = Vec::new();
                    let mut datas = Vec::new();
                    for _ in 0..derivation.right.len() {
                        if let Some(top) = stack.pop() {
                            datas.push(top.0.data.clone());
                            children.push(top.0);
                        } else {
                            Err("parsing error: stack is empty.")?;
                        }
                    }

                    let children: Vec<_> = children.into_iter().rev().collect();
                    let datas: Vec<_> = datas.into_iter().rev().collect();
                    let handler = self.handlers.get(&derivation).unwrap();

                    // if the left hand side is dummy start symbol
                    // do nothing
                    if derivation.left == Self::DUMMY_START_SYMBOL {
                        stack.push(NodePair(
                            ParsingTreeNode::build(
                                derivation.left.to_string(),
                                handler(datas),
                                children,
                            ),
                            0,
                        ));
                        continue;
                    }

                    // goto[top_state(stack), X]
                    if let Action::Shift(next_state) = self
                        .action_table
                        .get_action(stack.last().unwrap().1, &derivation.left)
                        .unwrap()
                    {
                        stack.push(NodePair(
                            ParsingTreeNode::build(
                                derivation.left.to_string(),
                                handler(datas),
                                children,
                            ),
                            *next_state,
                        ));
                    } else {
                        Err("parsing error: invalid Shift action.")?;
                    }
                }
                Some(Action::Accept) => {
                    let res = stack.pop().unwrap().0;
                    return Ok(res);
                }
                _ => {
                    Err("parsing error: unknown.")?;
                }
            }
        }
    }
}
