use serde::{Deserialize, Serialize};
use std::{collections::HashMap, error::Error, hash::Hash};

// declarations
// ======================

pub struct Foo {
    x: i32,
    y: i32,
}

// ======================

/// Token
/// must implement Clone and Token trait
/// Token trait is used to convert a token to a tree node
pub trait Token: Clone {
    fn to_tree_node(&self) -> ParsingTreeNode;
}

pub struct ParsingTreeNode {
    pub symbol_type: String,
    pub data: String,
    pub children: Vec<ParsingTreeNode>,
}

impl ParsingTreeNode {
    pub fn build(symbol_type: String, data: String, children: Vec<ParsingTreeNode>) -> Self {
        ParsingTreeNode {
            symbol_type,
            data,
            children,
        }
    }
}

/// NodePair
/// a pair of a node and a state.
/// (TreeNode, state)
pub struct NodePair(ParsingTreeNode, usize);
impl NodePair {
    pub fn new(node: ParsingTreeNode, state: usize) -> Self {
        NodePair(node, state)
    }
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ReduceDerivation {
    pub left: String,
    pub right: Vec<String>,
}

impl PartialEq for ReduceDerivation {
    fn eq(&self, other: &Self) -> bool {
        self.left == other.left && self.right == other.right
    }
}

impl Eq for ReduceDerivation {}

impl Hash for ReduceDerivation {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.left.hash(state);
        self.right.hash(state);
    }
}

impl ReduceDerivation {
    pub fn build(left: String, right: Vec<String>) -> Self {
        ReduceDerivation { left, right }
    }
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Action {
    Shift(usize),
    Reduce(ReduceDerivation),
    Accept,
    Error,
}

#[derive(Serialize, Deserialize)]
pub struct State {
    pub actions: HashMap<String, Action>,
}

impl State {
    pub fn new() -> Self {
        State {
            actions: HashMap::new(),
        }
    }
}

#[derive(Serialize, Deserialize, Default)]
pub struct ActionTable {
    pub states: Vec<State>,
}

impl ActionTable {
    pub fn get_action(&self, state: usize, symbol: &str) -> Option<&Action> {
        self.states[state].actions.get(symbol)
    }
}

#[derive(Default)]
pub struct RParser {
    action_table: ActionTable,
    handlers: HashMap<ReduceDerivation, Box<dyn Fn(Vec<String>) -> String>>,
    // variables
    // ======================
    pub a: i32,
    pub b: i64,
    // ======================
}

impl RParser {
    pub const END_SYMBOL: &'static str = "__$__";
    pub const EPSILON_SYMBOL: &'static str = "__EPSILON__";
    pub const DUMMY_START_SYMBOL: &'static str = "__DUMMY_START__";

    pub fn new() -> Self {
        // action table generated by rparser
        // ======================
        let action_table: ActionTable =  serde_json::from_str(r#"{"states":[{"actions":{"S":{"Shift":2},"__$__":"Accept","block":{"Shift":1},"left_curly_brace":{"Shift":3},"program":{"Shift":89}}},{"actions":{"__$__":{"Reduce":{"left":"program","right":["block"]}}}},{"actions":{"__$__":{"Reduce":{"left":"__DUMMY_START__","right":["S"]}}}},{"actions":{"while":{"Reduce":{"left":"decls","right":[]}},"if":{"Reduce":{"left":"decls","right":[]}},"break":{"Reduce":{"left":"decls","right":[]}},"decls":{"Shift":4},"do":{"Reduce":{"left":"decls","right":[]}},"id":{"Reduce":{"left":"decls","right":[]}},"basic":{"Reduce":{"left":"decls","right":[]}},"left_curly_brace":{"Reduce":{"left":"decls","right":[]}},"right_curly_brace":{"Reduce":{"left":"decls","right":[]}}}},{"actions":{"id":{"Reduce":{"left":"stmts","right":[]}},"do":{"Reduce":{"left":"stmts","right":[]}},"basic":{"Shift":87},"break":{"Reduce":{"left":"stmts","right":[]}},"while":{"Reduce":{"left":"stmts","right":[]}},"right_curly_brace":{"Reduce":{"left":"stmts","right":[]}},"stmts":{"Shift":5},"decl":{"Shift":88},"left_curly_brace":{"Reduce":{"left":"stmts","right":[]}},"if":{"Reduce":{"left":"stmts","right":[]}},"type":{"Shift":81}}},{"actions":{"if":{"Shift":11},"break":{"Shift":8},"left_curly_brace":{"Shift":3},"block":{"Shift":7},"right_curly_brace":{"Shift":6},"do":{"Shift":71},"while":{"Shift":62},"loc":{"Shift":66},"stmt":{"Shift":10},"id":{"Shift":27}}},{"actions":{"__$__":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"right_curly_brace":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"left_curly_brace":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"else":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"while":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"break":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"do":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"id":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}},"if":{"Reduce":{"left":"block","right":["left_curly_brace","decls","stmts","right_curly_brace"]}}}},{"actions":{"else":{"Reduce":{"left":"stmt","right":["block"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["block"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["block"]}},"while":{"Reduce":{"left":"stmt","right":["block"]}},"if":{"Reduce":{"left":"stmt","right":["block"]}},"id":{"Reduce":{"left":"stmt","right":["block"]}},"do":{"Reduce":{"left":"stmt","right":["block"]}},"break":{"Reduce":{"left":"stmt","right":["block"]}}}},{"actions":{";":{"Shift":9}}},{"actions":{"left_curly_brace":{"Reduce":{"left":"stmt","right":["break",";"]}},"while":{"Reduce":{"left":"stmt","right":["break",";"]}},"id":{"Reduce":{"left":"stmt","right":["break",";"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["break",";"]}},"break":{"Reduce":{"left":"stmt","right":["break",";"]}},"else":{"Reduce":{"left":"stmt","right":["break",";"]}},"do":{"Reduce":{"left":"stmt","right":["break",";"]}},"if":{"Reduce":{"left":"stmt","right":["break",";"]}}}},{"actions":{"while":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"right_curly_brace":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"id":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"break":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"do":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"if":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}},"left_curly_brace":{"Reduce":{"left":"stmts","right":["stmts","stmt"]}}}},{"actions":{"(":{"Shift":12}}},{"actions":{"false":{"Shift":30},"real":{"Shift":29},"!":{"Shift":33},"term":{"Shift":16},"bool":{"Shift":60},"rel":{"Shift":22},"num":{"Shift":28},"(":{"Shift":19},"id":{"Shift":27},"-":{"Shift":35},"unary":{"Shift":13},"loc":{"Shift":23},"join":{"Shift":57},"true":{"Shift":18},"factor":{"Shift":34},"equality":{"Shift":14},"expr":{"Shift":31}}},{"actions":{";":{"Reduce":{"left":"term","right":["unary"]}},"+":{"Reduce":{"left":"term","right":["unary"]}},"||":{"Reduce":{"left":"term","right":["unary"]}},"/":{"Reduce":{"left":"term","right":["unary"]}},"==":{"Reduce":{"left":"term","right":["unary"]}},"!=":{"Reduce":{"left":"term","right":["unary"]}},"<=":{"Reduce":{"left":"term","right":["unary"]}},">":{"Reduce":{"left":"term","right":["unary"]}},">=":{"Reduce":{"left":"term","right":["unary"]}},"*":{"Reduce":{"left":"term","right":["unary"]}},"&&":{"Reduce":{"left":"term","right":["unary"]}},"-":{"Reduce":{"left":"term","right":["unary"]}},"<":{"Reduce":{"left":"term","right":["unary"]}},")":{"Reduce":{"left":"term","right":["unary"]}}}},{"actions":{"&&":{"Reduce":{"left":"join","right":["equality"]}},"==":{"Shift":15},";":{"Reduce":{"left":"join","right":["equality"]}},"||":{"Reduce":{"left":"join","right":["equality"]}},"!=":{"Shift":54},")":{"Reduce":{"left":"join","right":["equality"]}}}},{"actions":{"real":{"Shift":29},"(":{"Shift":19},"expr":{"Shift":31},"true":{"Shift":18},"factor":{"Shift":34},"!":{"Shift":33},"false":{"Shift":30},"rel":{"Shift":59},"-":{"Shift":35},"id":{"Shift":27},"loc":{"Shift":23},"num":{"Shift":28},"unary":{"Shift":13},"term":{"Shift":16}}},{"actions":{"||":{"Reduce":{"left":"expr","right":["term"]}},"<=":{"Reduce":{"left":"expr","right":["term"]}},"!=":{"Reduce":{"left":"expr","right":["term"]}},"&&":{"Reduce":{"left":"expr","right":["term"]}},"==":{"Reduce":{"left":"expr","right":["term"]}},">=":{"Reduce":{"left":"expr","right":["term"]}},"+":{"Reduce":{"left":"expr","right":["term"]}},">":{"Reduce":{"left":"expr","right":["term"]}},";":{"Reduce":{"left":"expr","right":["term"]}},")":{"Reduce":{"left":"expr","right":["term"]}},"/":{"Shift":41},"-":{"Reduce":{"left":"expr","right":["term"]}},"*":{"Shift":17},"<":{"Reduce":{"left":"expr","right":["term"]}}}},{"actions":{"id":{"Shift":27},"(":{"Shift":19},"unary":{"Shift":58},"loc":{"Shift":23},"factor":{"Shift":34},"-":{"Shift":35},"false":{"Shift":30},"true":{"Shift":18},"real":{"Shift":29},"!":{"Shift":33},"num":{"Shift":28}}},{"actions":{";":{"Reduce":{"left":"factor","right":["true"]}},"!=":{"Reduce":{"left":"factor","right":["true"]}},"*":{"Reduce":{"left":"factor","right":["true"]}},"/":{"Reduce":{"left":"factor","right":["true"]}},">":{"Reduce":{"left":"factor","right":["true"]}},"||":{"Reduce":{"left":"factor","right":["true"]}},"<":{"Reduce":{"left":"factor","right":["true"]}},"+":{"Reduce":{"left":"factor","right":["true"]}},"==":{"Reduce":{"left":"factor","right":["true"]}},"-":{"Reduce":{"left":"factor","right":["true"]}},"&&":{"Reduce":{"left":"factor","right":["true"]}},">=":{"Reduce":{"left":"factor","right":["true"]}},"<=":{"Reduce":{"left":"factor","right":["true"]}},")":{"Reduce":{"left":"factor","right":["true"]}}}},{"actions":{"factor":{"Shift":34},"bool":{"Shift":20},"true":{"Shift":18},"term":{"Shift":16},"false":{"Shift":30},"-":{"Shift":35},"!":{"Shift":33},"id":{"Shift":27},"num":{"Shift":28},"rel":{"Shift":22},"real":{"Shift":29},"loc":{"Shift":23},"(":{"Shift":19},"expr":{"Shift":31},"join":{"Shift":57},"equality":{"Shift":14},"unary":{"Shift":13}}},{"actions":{"||":{"Shift":21},")":{"Shift":56}}},{"actions":{"expr":{"Shift":31},"loc":{"Shift":23},"real":{"Shift":29},"(":{"Shift":19},"!":{"Shift":33},"-":{"Shift":35},"false":{"Shift":30},"factor":{"Shift":34},"join":{"Shift":51},"id":{"Shift":27},"true":{"Shift":18},"num":{"Shift":28},"equality":{"Shift":14},"unary":{"Shift":13},"term":{"Shift":16},"rel":{"Shift":22}}},{"actions":{")":{"Reduce":{"left":"equality","right":["rel"]}},"==":{"Reduce":{"left":"equality","right":["rel"]}},"&&":{"Reduce":{"left":"equality","right":["rel"]}},"||":{"Reduce":{"left":"equality","right":["rel"]}},"!=":{"Reduce":{"left":"equality","right":["rel"]}},";":{"Reduce":{"left":"equality","right":["rel"]}}}},{"actions":{">":{"Reduce":{"left":"factor","right":["loc"]}},";":{"Reduce":{"left":"factor","right":["loc"]}},">=":{"Reduce":{"left":"factor","right":["loc"]}},"==":{"Reduce":{"left":"factor","right":["loc"]}},"&&":{"Reduce":{"left":"factor","right":["loc"]}},"/":{"Reduce":{"left":"factor","right":["loc"]}},"<=":{"Reduce":{"left":"factor","right":["loc"]}},"*":{"Reduce":{"left":"factor","right":["loc"]}},"-":{"Reduce":{"left":"factor","right":["loc"]}},"!=":{"Reduce":{"left":"factor","right":["loc"]}},")":{"Reduce":{"left":"factor","right":["loc"]}},"<":{"Reduce":{"left":"factor","right":["loc"]}},"[":{"Shift":24},"+":{"Reduce":{"left":"factor","right":["loc"]}},"||":{"Reduce":{"left":"factor","right":["loc"]}}}},{"actions":{"num":{"Shift":25}}},{"actions":{"]":{"Shift":26}}},{"actions":{"+":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"&&":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"!=":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"=":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},">=":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"||":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},">":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"*":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"[":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},")":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"-":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"==":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"<":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},";":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"/":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}},"<=":{"Reduce":{"left":"loc","right":["loc","[","num","]"]}}}},{"actions":{"+":{"Reduce":{"left":"loc","right":["id"]}},"<=":{"Reduce":{"left":"loc","right":["id"]}},"||":{"Reduce":{"left":"loc","right":["id"]}},"=":{"Reduce":{"left":"loc","right":["id"]}},"!=":{"Reduce":{"left":"loc","right":["id"]}},"<":{"Reduce":{"left":"loc","right":["id"]}},"&&":{"Reduce":{"left":"loc","right":["id"]}},"/":{"Reduce":{"left":"loc","right":["id"]}},"==":{"Reduce":{"left":"loc","right":["id"]}},">=":{"Reduce":{"left":"loc","right":["id"]}},";":{"Reduce":{"left":"loc","right":["id"]}},">":{"Reduce":{"left":"loc","right":["id"]}},"[":{"Reduce":{"left":"loc","right":["id"]}},")":{"Reduce":{"left":"loc","right":["id"]}},"*":{"Reduce":{"left":"loc","right":["id"]}},"-":{"Reduce":{"left":"loc","right":["id"]}}}},{"actions":{"!=":{"Reduce":{"left":"factor","right":["num"]}},"<":{"Reduce":{"left":"factor","right":["num"]}},"+":{"Reduce":{"left":"factor","right":["num"]}},"/":{"Reduce":{"left":"factor","right":["num"]}},"-":{"Reduce":{"left":"factor","right":["num"]}},")":{"Reduce":{"left":"factor","right":["num"]}},"==":{"Reduce":{"left":"factor","right":["num"]}},">=":{"Reduce":{"left":"factor","right":["num"]}},";":{"Reduce":{"left":"factor","right":["num"]}},"||":{"Reduce":{"left":"factor","right":["num"]}},"&&":{"Reduce":{"left":"factor","right":["num"]}},"*":{"Reduce":{"left":"factor","right":["num"]}},"<=":{"Reduce":{"left":"factor","right":["num"]}},">":{"Reduce":{"left":"factor","right":["num"]}}}},{"actions":{"&&":{"Reduce":{"left":"factor","right":["real"]}},"/":{"Reduce":{"left":"factor","right":["real"]}},"<":{"Reduce":{"left":"factor","right":["real"]}},"!=":{"Reduce":{"left":"factor","right":["real"]}},">=":{"Reduce":{"left":"factor","right":["real"]}},";":{"Reduce":{"left":"factor","right":["real"]}},"||":{"Reduce":{"left":"factor","right":["real"]}},")":{"Reduce":{"left":"factor","right":["real"]}},"-":{"Reduce":{"left":"factor","right":["real"]}},"*":{"Reduce":{"left":"factor","right":["real"]}},"+":{"Reduce":{"left":"factor","right":["real"]}},"==":{"Reduce":{"left":"factor","right":["real"]}},">":{"Reduce":{"left":"factor","right":["real"]}},"<=":{"Reduce":{"left":"factor","right":["real"]}}}},{"actions":{"<=":{"Reduce":{"left":"factor","right":["false"]}},"||":{"Reduce":{"left":"factor","right":["false"]}},";":{"Reduce":{"left":"factor","right":["false"]}},"<":{"Reduce":{"left":"factor","right":["false"]}},")":{"Reduce":{"left":"factor","right":["false"]}},"==":{"Reduce":{"left":"factor","right":["false"]}},"*":{"Reduce":{"left":"factor","right":["false"]}},"-":{"Reduce":{"left":"factor","right":["false"]}},">":{"Reduce":{"left":"factor","right":["false"]}},">=":{"Reduce":{"left":"factor","right":["false"]}},"&&":{"Reduce":{"left":"factor","right":["false"]}},"+":{"Reduce":{"left":"factor","right":["false"]}},"!=":{"Reduce":{"left":"factor","right":["false"]}},"/":{"Reduce":{"left":"factor","right":["false"]}}}},{"actions":{"&&":{"Reduce":{"left":"rel","right":["expr"]}},")":{"Reduce":{"left":"rel","right":["expr"]}},"<":{"Shift":32},">=":{"Shift":45},"<=":{"Shift":47},">":{"Shift":49},";":{"Reduce":{"left":"rel","right":["expr"]}},"!=":{"Reduce":{"left":"rel","right":["expr"]}},"==":{"Reduce":{"left":"rel","right":["expr"]}},"||":{"Reduce":{"left":"rel","right":["expr"]}},"-":{"Shift":43},"+":{"Shift":39}}},{"actions":{"term":{"Shift":16},"id":{"Shift":27},"false":{"Shift":30},"unary":{"Shift":13},"-":{"Shift":35},"expr":{"Shift":38},"(":{"Shift":19},"true":{"Shift":18},"loc":{"Shift":23},"!":{"Shift":33},"real":{"Shift":29},"num":{"Shift":28},"factor":{"Shift":34}}},{"actions":{"!":{"Shift":33},"id":{"Shift":27},"true":{"Shift":18},"loc":{"Shift":23},"-":{"Shift":35},"unary":{"Shift":37},"factor":{"Shift":34},"(":{"Shift":19},"false":{"Shift":30},"num":{"Shift":28},"real":{"Shift":29}}},{"actions":{"<":{"Reduce":{"left":"unary","right":["factor"]}},"+":{"Reduce":{"left":"unary","right":["factor"]}},"*":{"Reduce":{"left":"unary","right":["factor"]}},")":{"Reduce":{"left":"unary","right":["factor"]}},"||":{"Reduce":{"left":"unary","right":["factor"]}},">":{"Reduce":{"left":"unary","right":["factor"]}},"&&":{"Reduce":{"left":"unary","right":["factor"]}},"==":{"Reduce":{"left":"unary","right":["factor"]}},"!=":{"Reduce":{"left":"unary","right":["factor"]}},"<=":{"Reduce":{"left":"unary","right":["factor"]}},";":{"Reduce":{"left":"unary","right":["factor"]}},"-":{"Reduce":{"left":"unary","right":["factor"]}},">=":{"Reduce":{"left":"unary","right":["factor"]}},"/":{"Reduce":{"left":"unary","right":["factor"]}}}},{"actions":{"loc":{"Shift":23},"(":{"Shift":19},"false":{"Shift":30},"true":{"Shift":18},"!":{"Shift":33},"unary":{"Shift":36},"num":{"Shift":28},"-":{"Shift":35},"id":{"Shift":27},"real":{"Shift":29},"factor":{"Shift":34}}},{"actions":{">=":{"Reduce":{"left":"unary","right":["-","unary"]}},">":{"Reduce":{"left":"unary","right":["-","unary"]}},"||":{"Reduce":{"left":"unary","right":["-","unary"]}},";":{"Reduce":{"left":"unary","right":["-","unary"]}},"/":{"Reduce":{"left":"unary","right":["-","unary"]}},"*":{"Reduce":{"left":"unary","right":["-","unary"]}},"-":{"Reduce":{"left":"unary","right":["-","unary"]}},"==":{"Reduce":{"left":"unary","right":["-","unary"]}},"<=":{"Reduce":{"left":"unary","right":["-","unary"]}},"<":{"Reduce":{"left":"unary","right":["-","unary"]}},"!=":{"Reduce":{"left":"unary","right":["-","unary"]}},"&&":{"Reduce":{"left":"unary","right":["-","unary"]}},"+":{"Reduce":{"left":"unary","right":["-","unary"]}},")":{"Reduce":{"left":"unary","right":["-","unary"]}}}},{"actions":{"+":{"Reduce":{"left":"unary","right":["!","unary"]}},"*":{"Reduce":{"left":"unary","right":["!","unary"]}},"<":{"Reduce":{"left":"unary","right":["!","unary"]}},">=":{"Reduce":{"left":"unary","right":["!","unary"]}},"-":{"Reduce":{"left":"unary","right":["!","unary"]}},"/":{"Reduce":{"left":"unary","right":["!","unary"]}},">":{"Reduce":{"left":"unary","right":["!","unary"]}},"==":{"Reduce":{"left":"unary","right":["!","unary"]}},";":{"Reduce":{"left":"unary","right":["!","unary"]}},")":{"Reduce":{"left":"unary","right":["!","unary"]}},"!=":{"Reduce":{"left":"unary","right":["!","unary"]}},"<=":{"Reduce":{"left":"unary","right":["!","unary"]}},"&&":{"Reduce":{"left":"unary","right":["!","unary"]}},"||":{"Reduce":{"left":"unary","right":["!","unary"]}}}},{"actions":{";":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},"||":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},"-":{"Shift":43},"&&":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},"+":{"Shift":39},"!=":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},"==":{"Reduce":{"left":"rel","right":["expr","<","expr"]}},")":{"Reduce":{"left":"rel","right":["expr","<","expr"]}}}},{"actions":{"loc":{"Shift":23},"-":{"Shift":35},"term":{"Shift":40},"true":{"Shift":18},"unary":{"Shift":13},"id":{"Shift":27},"num":{"Shift":28},"(":{"Shift":19},"false":{"Shift":30},"!":{"Shift":33},"real":{"Shift":29},"factor":{"Shift":34}}},{"actions":{"*":{"Shift":17},"/":{"Shift":41},"==":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"||":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"!=":{"Reduce":{"left":"expr","right":["expr","+","term"]}},";":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"<":{"Reduce":{"left":"expr","right":["expr","+","term"]}},")":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"+":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"&&":{"Reduce":{"left":"expr","right":["expr","+","term"]}},">":{"Reduce":{"left":"expr","right":["expr","+","term"]}},">=":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"-":{"Reduce":{"left":"expr","right":["expr","+","term"]}},"<=":{"Reduce":{"left":"expr","right":["expr","+","term"]}}}},{"actions":{"real":{"Shift":29},"false":{"Shift":30},"unary":{"Shift":42},"-":{"Shift":35},"!":{"Shift":33},"loc":{"Shift":23},"true":{"Shift":18},"num":{"Shift":28},"id":{"Shift":27},"factor":{"Shift":34},"(":{"Shift":19}}},{"actions":{"==":{"Reduce":{"left":"term","right":["term","/","unary"]}},"+":{"Reduce":{"left":"term","right":["term","/","unary"]}},";":{"Reduce":{"left":"term","right":["term","/","unary"]}},"/":{"Reduce":{"left":"term","right":["term","/","unary"]}},"<=":{"Reduce":{"left":"term","right":["term","/","unary"]}},"!=":{"Reduce":{"left":"term","right":["term","/","unary"]}},"&&":{"Reduce":{"left":"term","right":["term","/","unary"]}},">=":{"Reduce":{"left":"term","right":["term","/","unary"]}},">":{"Reduce":{"left":"term","right":["term","/","unary"]}},"-":{"Reduce":{"left":"term","right":["term","/","unary"]}},"||":{"Reduce":{"left":"term","right":["term","/","unary"]}},"<":{"Reduce":{"left":"term","right":["term","/","unary"]}},"*":{"Reduce":{"left":"term","right":["term","/","unary"]}},")":{"Reduce":{"left":"term","right":["term","/","unary"]}}}},{"actions":{"factor":{"Shift":34},"id":{"Shift":27},"false":{"Shift":30},"unary":{"Shift":13},"-":{"Shift":35},"num":{"Shift":28},"loc":{"Shift":23},"term":{"Shift":44},"true":{"Shift":18},"(":{"Shift":19},"real":{"Shift":29},"!":{"Shift":33}}},{"actions":{"==":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"&&":{"Reduce":{"left":"expr","right":["expr","-","term"]}},";":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"||":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"<":{"Reduce":{"left":"expr","right":["expr","-","term"]}},">":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"!=":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"+":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"-":{"Reduce":{"left":"expr","right":["expr","-","term"]}},">=":{"Reduce":{"left":"expr","right":["expr","-","term"]}},")":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"<=":{"Reduce":{"left":"expr","right":["expr","-","term"]}},"/":{"Shift":41},"*":{"Shift":17}}},{"actions":{"-":{"Shift":35},"loc":{"Shift":23},"unary":{"Shift":13},"!":{"Shift":33},"false":{"Shift":30},"num":{"Shift":28},"true":{"Shift":18},"factor":{"Shift":34},"expr":{"Shift":46},"(":{"Shift":19},"real":{"Shift":29},"term":{"Shift":16},"id":{"Shift":27}}},{"actions":{"==":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},"!=":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},";":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},"||":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},"+":{"Shift":39},"-":{"Shift":43},")":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}},"&&":{"Reduce":{"left":"rel","right":["expr",">=","expr"]}}}},{"actions":{"loc":{"Shift":23},"false":{"Shift":30},"expr":{"Shift":48},"term":{"Shift":16},"num":{"Shift":28},"factor":{"Shift":34},"unary":{"Shift":13},"!":{"Shift":33},"real":{"Shift":29},"(":{"Shift":19},"id":{"Shift":27},"true":{"Shift":18},"-":{"Shift":35}}},{"actions":{"==":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},"!=":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},"+":{"Shift":39},"-":{"Shift":43},";":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},"||":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},"&&":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}},")":{"Reduce":{"left":"rel","right":["expr","<=","expr"]}}}},{"actions":{"factor":{"Shift":34},"num":{"Shift":28},"id":{"Shift":27},"-":{"Shift":35},"false":{"Shift":30},"expr":{"Shift":50},"unary":{"Shift":13},"!":{"Shift":33},"(":{"Shift":19},"real":{"Shift":29},"term":{"Shift":16},"loc":{"Shift":23},"true":{"Shift":18}}},{"actions":{"-":{"Shift":43},"!=":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},"+":{"Shift":39},"||":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},"&&":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},"==":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},")":{"Reduce":{"left":"rel","right":["expr",">","expr"]}},";":{"Reduce":{"left":"rel","right":["expr",">","expr"]}}}},{"actions":{"||":{"Reduce":{"left":"bool","right":["bool","||","join"]}},";":{"Reduce":{"left":"bool","right":["bool","||","join"]}},"&&":{"Shift":52},")":{"Reduce":{"left":"bool","right":["bool","||","join"]}}}},{"actions":{"id":{"Shift":27},"true":{"Shift":18},"equality":{"Shift":53},"factor":{"Shift":34},"num":{"Shift":28},"real":{"Shift":29},"expr":{"Shift":31},"false":{"Shift":30},"(":{"Shift":19},"loc":{"Shift":23},"term":{"Shift":16},"unary":{"Shift":13},"-":{"Shift":35},"rel":{"Shift":22},"!":{"Shift":33}}},{"actions":{";":{"Reduce":{"left":"join","right":["join","&&","equality"]}},"==":{"Shift":15},"&&":{"Reduce":{"left":"join","right":["join","&&","equality"]}},"||":{"Reduce":{"left":"join","right":["join","&&","equality"]}},")":{"Reduce":{"left":"join","right":["join","&&","equality"]}},"!=":{"Shift":54}}},{"actions":{"true":{"Shift":18},"rel":{"Shift":55},"false":{"Shift":30},"expr":{"Shift":31},"factor":{"Shift":34},"real":{"Shift":29},"-":{"Shift":35},"(":{"Shift":19},"num":{"Shift":28},"unary":{"Shift":13},"!":{"Shift":33},"loc":{"Shift":23},"term":{"Shift":16},"id":{"Shift":27}}},{"actions":{"||":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},")":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},"!=":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},"&&":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},";":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}},"==":{"Reduce":{"left":"equality","right":["equality","!=","rel"]}}}},{"actions":{"/":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"<=":{"Reduce":{"left":"factor","right":["(","bool",")"]}},">":{"Reduce":{"left":"factor","right":["(","bool",")"]}},";":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"<":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"==":{"Reduce":{"left":"factor","right":["(","bool",")"]}},">=":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"||":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"*":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"!=":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"-":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"+":{"Reduce":{"left":"factor","right":["(","bool",")"]}},")":{"Reduce":{"left":"factor","right":["(","bool",")"]}},"&&":{"Reduce":{"left":"factor","right":["(","bool",")"]}}}},{"actions":{")":{"Reduce":{"left":"bool","right":["join"]}},"&&":{"Shift":52},";":{"Reduce":{"left":"bool","right":["join"]}},"||":{"Reduce":{"left":"bool","right":["join"]}}}},{"actions":{"+":{"Reduce":{"left":"term","right":["term","*","unary"]}},";":{"Reduce":{"left":"term","right":["term","*","unary"]}},"-":{"Reduce":{"left":"term","right":["term","*","unary"]}},"||":{"Reduce":{"left":"term","right":["term","*","unary"]}},"<=":{"Reduce":{"left":"term","right":["term","*","unary"]}},"*":{"Reduce":{"left":"term","right":["term","*","unary"]}},")":{"Reduce":{"left":"term","right":["term","*","unary"]}},">":{"Reduce":{"left":"term","right":["term","*","unary"]}},"&&":{"Reduce":{"left":"term","right":["term","*","unary"]}},"<":{"Reduce":{"left":"term","right":["term","*","unary"]}},"!=":{"Reduce":{"left":"term","right":["term","*","unary"]}},"==":{"Reduce":{"left":"term","right":["term","*","unary"]}},"/":{"Reduce":{"left":"term","right":["term","*","unary"]}},">=":{"Reduce":{"left":"term","right":["term","*","unary"]}}}},{"actions":{"!=":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},"&&":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},"==":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},"||":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},";":{"Reduce":{"left":"equality","right":["equality","==","rel"]}},")":{"Reduce":{"left":"equality","right":["equality","==","rel"]}}}},{"actions":{")":{"Shift":61},"||":{"Shift":21}}},{"actions":{"break":{"Shift":8},"id":{"Shift":27},"while":{"Shift":62},"stmt":{"Shift":78},"loc":{"Shift":66},"do":{"Shift":71},"if":{"Shift":11},"block":{"Shift":7},"left_curly_brace":{"Shift":3}}},{"actions":{"(":{"Shift":63}}},{"actions":{"equality":{"Shift":14},"-":{"Shift":35},"loc":{"Shift":23},"join":{"Shift":57},"id":{"Shift":27},"expr":{"Shift":31},"unary":{"Shift":13},"term":{"Shift":16},"num":{"Shift":28},"true":{"Shift":18},"real":{"Shift":29},"bool":{"Shift":64},"factor":{"Shift":34},"rel":{"Shift":22},"!":{"Shift":33},"(":{"Shift":19},"false":{"Shift":30}}},{"actions":{"||":{"Shift":21},")":{"Shift":65}}},{"actions":{"while":{"Shift":62},"if":{"Shift":11},"id":{"Shift":27},"loc":{"Shift":66},"stmt":{"Shift":70},"left_curly_brace":{"Shift":3},"do":{"Shift":71},"block":{"Shift":7},"break":{"Shift":8}}},{"actions":{"=":{"Shift":67},"[":{"Shift":24}}},{"actions":{"unary":{"Shift":13},"id":{"Shift":27},"equality":{"Shift":14},"!":{"Shift":33},"term":{"Shift":16},"(":{"Shift":19},"join":{"Shift":57},"num":{"Shift":28},"false":{"Shift":30},"true":{"Shift":18},"-":{"Shift":35},"loc":{"Shift":23},"bool":{"Shift":68},"rel":{"Shift":22},"expr":{"Shift":31},"factor":{"Shift":34},"real":{"Shift":29}}},{"actions":{";":{"Shift":69},"||":{"Shift":21}}},{"actions":{"if":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"id":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"while":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"do":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"break":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}},"else":{"Reduce":{"left":"stmt","right":["loc","=","bool",";"]}}}},{"actions":{"id":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"while":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"else":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"do":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"break":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"if":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["while","(","bool",")","stmt"]}}}},{"actions":{"left_curly_brace":{"Shift":3},"id":{"Shift":27},"block":{"Shift":7},"if":{"Shift":11},"do":{"Shift":71},"while":{"Shift":62},"break":{"Shift":8},"loc":{"Shift":66},"stmt":{"Shift":72}}},{"actions":{"while":{"Shift":73}}},{"actions":{"(":{"Shift":74}}},{"actions":{"real":{"Shift":29},"factor":{"Shift":34},"false":{"Shift":30},"num":{"Shift":28},"unary":{"Shift":13},"id":{"Shift":27},"!":{"Shift":33},"true":{"Shift":18},"equality":{"Shift":14},"(":{"Shift":19},"join":{"Shift":57},"-":{"Shift":35},"term":{"Shift":16},"expr":{"Shift":31},"rel":{"Shift":22},"loc":{"Shift":23},"bool":{"Shift":75}}},{"actions":{"||":{"Shift":21},")":{"Shift":76}}},{"actions":{";":{"Shift":77}}},{"actions":{"while":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"id":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"do":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"break":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"else":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}},"if":{"Reduce":{"left":"stmt","right":["do","stmt","while","(","bool",")",";"]}}}},{"actions":{"break":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"else":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"while":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"do":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"right_curly_brace":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"if":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}},"id":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt"]}}}},{"actions":{"loc":{"Shift":66},"block":{"Shift":7},"break":{"Shift":8},"if":{"Shift":11},"do":{"Shift":71},"id":{"Shift":27},"while":{"Shift":62},"left_curly_brace":{"Shift":3},"stmt":{"Shift":80}}},{"actions":{"right_curly_brace":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"break":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"else":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"id":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"left_curly_brace":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"while":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"do":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}},"if":{"Reduce":{"left":"stmt","right":["if","(","bool",")","stmt","else","stmt"]}}}},{"actions":{"id":{"Shift":85},"[":{"Shift":82}}},{"actions":{"num":{"Shift":83}}},{"actions":{"]":{"Shift":84}}},{"actions":{"[":{"Reduce":{"left":"type","right":["type","[","num","]"]}},"id":{"Reduce":{"left":"type","right":["type","[","num","]"]}}}},{"actions":{";":{"Shift":86}}},{"actions":{"id":{"Reduce":{"left":"decl","right":["type","id",";"]}},"if":{"Reduce":{"left":"decl","right":["type","id",";"]}},"right_curly_brace":{"Reduce":{"left":"decl","right":["type","id",";"]}},"break":{"Reduce":{"left":"decl","right":["type","id",";"]}},"do":{"Reduce":{"left":"decl","right":["type","id",";"]}},"left_curly_brace":{"Reduce":{"left":"decl","right":["type","id",";"]}},"while":{"Reduce":{"left":"decl","right":["type","id",";"]}},"basic":{"Reduce":{"left":"decl","right":["type","id",";"]}}}},{"actions":{"id":{"Reduce":{"left":"type","right":["basic"]}},"[":{"Reduce":{"left":"type","right":["basic"]}}}},{"actions":{"break":{"Reduce":{"left":"decls","right":["decls","decl"]}},"left_curly_brace":{"Reduce":{"left":"decls","right":["decls","decl"]}},"right_curly_brace":{"Reduce":{"left":"decls","right":["decls","decl"]}},"id":{"Reduce":{"left":"decls","right":["decls","decl"]}},"do":{"Reduce":{"left":"decls","right":["decls","decl"]}},"basic":{"Reduce":{"left":"decls","right":["decls","decl"]}},"while":{"Reduce":{"left":"decls","right":["decls","decl"]}},"if":{"Reduce":{"left":"decls","right":["decls","decl"]}}}},{"actions":{"__$__":{"Reduce":{"left":"S","right":["program"]}}}}]}"#).unwrap();
        // ======================

        let mut handlers: HashMap<ReduceDerivation, Box<dyn Fn(Vec<String>) -> String>> =
            HashMap::new();

        // handlers generated by rparser
        // ======================
        handlers.insert(
            ReduceDerivation::build("S".into(), vec!["program".into()]),
            Box::new(|datas| {
                println!("S -> program");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("program".into(), vec!["block".into()]),
            Box::new(|datas| {
                println!("program -> block");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "block".into(),
                vec![
                    "left_curly_brace".into(),
                    "decls".into(),
                    "stmts".into(),
                    "right_curly_brace".into(),
                ],
            ),
            Box::new(|datas| {
                println!("block -> left_curly_brace decls stmts right_curly_brace");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("decls".into(), vec!["decls".into(), "decl".into()]),
            Box::new(|datas| {
                println!("decls -> decls decl");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("decls".into(), vec![]),
            Box::new(|datas| {
                println!("decls -> ε");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("decl".into(), vec!["type".into(), "id".into(), ";".into()]),
            Box::new(|datas| {
                println!("decl -> type id ;");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "type".into(),
                vec!["type".into(), "[".into(), "num".into(), "]".into()],
            ),
            Box::new(|datas| {
                println!("type -> type [ num ]");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("type".into(), vec!["basic".into()]),
            Box::new(|datas| {
                println!("type -> basic");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("stmts".into(), vec!["stmts".into(), "stmt".into()]),
            Box::new(|datas| {
                println!("stmts -> stmts stmt");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("stmts".into(), vec![]),
            Box::new(|datas| {
                println!("stmts -> ε");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec!["loc".into(), "=".into(), "bool".into(), ";".into()],
            ),
            Box::new(|datas| {
                println!("stmt -> loc = bool ;");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec![
                    "if".into(),
                    "(".into(),
                    "bool".into(),
                    ")".into(),
                    "stmt".into(),
                ],
            ),
            Box::new(|datas| {
                println!("stmt -> if ( bool ) stmt");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec![
                    "if".into(),
                    "(".into(),
                    "bool".into(),
                    ")".into(),
                    "stmt".into(),
                    "else".into(),
                    "stmt".into(),
                ],
            ),
            Box::new(|datas| {
                println!("stmt -> if ( bool ) stmt else stmt");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec![
                    "while".into(),
                    "(".into(),
                    "bool".into(),
                    ")".into(),
                    "stmt".into(),
                ],
            ),
            Box::new(|datas| {
                println!("stmt -> while ( bool ) stmt");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "stmt".into(),
                vec![
                    "do".into(),
                    "stmt".into(),
                    "while".into(),
                    "(".into(),
                    "bool".into(),
                    ")".into(),
                    ";".into(),
                ],
            ),
            Box::new(|datas| {
                println!("stmt -> do stmt while ( bool ) ;");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("stmt".into(), vec!["break".into(), ";".into()]),
            Box::new(|datas| {
                println!("stmt -> break ;");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("stmt".into(), vec!["block".into()]),
            Box::new(|datas| {
                println!("stmt -> block");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "loc".into(),
                vec!["loc".into(), "[".into(), "num".into(), "]".into()],
            ),
            Box::new(|datas| {
                println!("loc -> loc [ num ]");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("loc".into(), vec!["id".into()]),
            Box::new(|datas| {
                println!("loc -> id");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "bool".into(),
                vec!["bool".into(), "||".into(), "join".into()],
            ),
            Box::new(|datas| {
                println!("bool -> bool || join");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("bool".into(), vec!["join".into()]),
            Box::new(|datas| {
                println!("bool -> join");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "join".into(),
                vec!["join".into(), "&&".into(), "equality".into()],
            ),
            Box::new(|datas| {
                println!("join -> join && equality");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("join".into(), vec!["equality".into()]),
            Box::new(|datas| {
                println!("join -> equality");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "equality".into(),
                vec!["equality".into(), "==".into(), "rel".into()],
            ),
            Box::new(|datas| {
                println!("equality -> equality == rel");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "equality".into(),
                vec!["equality".into(), "!=".into(), "rel".into()],
            ),
            Box::new(|datas| {
                println!("equality -> equality != rel");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("equality".into(), vec!["rel".into()]),
            Box::new(|datas| {
                println!("equality -> rel");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("rel".into(), vec!["expr".into(), "<".into(), "expr".into()]),
            Box::new(|datas| {
                println!("rel -> expr < expr");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "rel".into(),
                vec!["expr".into(), "<=".into(), "expr".into()],
            ),
            Box::new(|datas| {
                println!("rel -> expr <= expr");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "rel".into(),
                vec!["expr".into(), ">=".into(), "expr".into()],
            ),
            Box::new(|datas| {
                println!("rel -> expr >= expr");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("rel".into(), vec!["expr".into(), ">".into(), "expr".into()]),
            Box::new(|datas| {
                println!("rel -> expr > expr");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("rel".into(), vec!["expr".into()]),
            Box::new(|datas| {
                println!("rel -> expr");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "expr".into(),
                vec!["expr".into(), "+".into(), "term".into()],
            ),
            Box::new(|datas| {
                println!("expr -> expr + term");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "expr".into(),
                vec!["expr".into(), "-".into(), "term".into()],
            ),
            Box::new(|datas| {
                println!("expr -> expr - term");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("expr".into(), vec!["term".into()]),
            Box::new(|datas| {
                println!("expr -> term");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "term".into(),
                vec!["term".into(), "*".into(), "unary".into()],
            ),
            Box::new(|datas| {
                println!("term -> term * unary");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build(
                "term".into(),
                vec!["term".into(), "/".into(), "unary".into()],
            ),
            Box::new(|datas| {
                println!("term -> term / unary");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("term".into(), vec!["unary".into()]),
            Box::new(|datas| {
                println!("term -> unary");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("unary".into(), vec!["!".into(), "unary".into()]),
            Box::new(|datas| {
                println!("unary -> ! unary");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("unary".into(), vec!["-".into(), "unary".into()]),
            Box::new(|datas| {
                println!("unary -> - unary");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("unary".into(), vec!["factor".into()]),
            Box::new(|datas| {
                println!("unary -> factor");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["(".into(), "bool".into(), ")".into()]),
            Box::new(|datas| {
                println!("factor -> ( bool )");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["loc".into()]),
            Box::new(|datas| {
                println!("factor -> loc");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["num".into()]),
            Box::new(|datas| {
                println!("factor -> num");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["real".into()]),
            Box::new(|datas| {
                println!("factor -> real");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["true".into()]),
            Box::new(|datas| {
                println!("factor -> true");
                "".to_string()
            }),
        );
        handlers.insert(
            ReduceDerivation::build("factor".into(), vec!["false".into()]),
            Box::new(|datas| {
                println!("factor -> false");
                "".to_string()
            }),
        );
        // ======================

        handlers.insert(
            ReduceDerivation::build(Self::DUMMY_START_SYMBOL.into(), vec!["S".into()]),
            Box::new(|vals| vals[0].clone()),
        );

        let mut res: RParser = RParser::default();
        res.action_table = action_table;
        res.handlers = handlers;
        res
    }

    // do shift-reduce parsing
    pub fn parse<T>(&self, tokens: Vec<T>) -> Result<ParsingTreeNode, Box<dyn Error>>
    where
        T: Token,
    {
        let mut shift_index = 0;
        let mut stack: Vec<NodePair> = Vec::new();

        stack.push(NodePair::new(
            ParsingTreeNode::build(Self::DUMMY_START_SYMBOL.into(), String::new(), Vec::new()),
            0,
        ));

        loop {
            let token_node = &tokens[shift_index].to_tree_node();

            let action = self
                .action_table
                .get_action(stack.last().unwrap().1, &token_node.symbol_type);

            match action {
                Some(Action::Shift(next_state)) => {
                    // shift
                    stack.push(NodePair::new(
                        tokens[shift_index].to_tree_node(),
                        *next_state,
                    ));
                    shift_index += 1;
                }
                Some(Action::Reduce(derivation)) => {
                    // pop right hand
                    let mut children: Vec<ParsingTreeNode> = Vec::new();
                    let mut datas = Vec::new();
                    for _ in 0..derivation.right.len() {
                        if let Some(top) = stack.pop() {
                            datas.push(top.0.data.clone());
                            children.push(top.0);
                        } else {
                            Err("parsing error: stack is empty.")?;
                        }
                    }

                    let children: Vec<_> = children.into_iter().rev().collect();
                    let datas: Vec<_> = datas.into_iter().rev().collect();
                    let handler = self.handlers.get(&derivation).unwrap();

                    // if the left hand side is dummy start symbol
                    // do nothing
                    if derivation.left == Self::DUMMY_START_SYMBOL {
                        stack.push(NodePair(
                            ParsingTreeNode::build(
                                derivation.left.to_string(),
                                handler(datas),
                                children,
                            ),
                            0,
                        ));
                        continue;
                    }

                    // goto[top_state(stack), X]
                    if let Action::Shift(next_state) = self
                        .action_table
                        .get_action(stack.last().unwrap().1, &derivation.left)
                        .unwrap()
                    {
                        stack.push(NodePair(
                            ParsingTreeNode::build(
                                derivation.left.to_string(),
                                handler(datas),
                                children,
                            ),
                            *next_state,
                        ));
                    } else {
                        Err("parsing error: invalid Shift action.")?;
                    }
                }
                Some(Action::Accept) => {
                    let res = stack.pop().unwrap().0;
                    return Ok(res);
                }
                _ => {
                    Err("parsing error: unknown.")?;
                }
            }
        }
    }
}
